"""add_workspace_settings_wave2

Revision ID: 06c9b4b1dcda
Revises: b7e2f4a9c1d3
Create Date: 2026-08-26 19:26:57.154795

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "06c9b4b1dcda"
down_revision: Union[str, None] = "b7e2f4a9c1d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first, set defaults, then make NOT NULL
    op.add_column(
        "workspaces", sa.Column("credit_warning_days", sa.Integer(), nullable=True)
    )
    op.add_column(
        "workspaces", sa.Column("block_po_on_hold", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "workspaces", sa.Column("block_do_on_hold", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "workspaces",
        sa.Column(
            "price_tolerance_percent", sa.Numeric(precision=5, scale=2), nullable=True
        ),
    )

    # Set defaults for existing rows
    op.execute(
        "UPDATE workspaces SET credit_warning_days = 30 WHERE credit_warning_days IS NULL"
    )
    op.execute(
        "UPDATE workspaces SET block_po_on_hold = true WHERE block_po_on_hold IS NULL"
    )
    op.execute(
        "UPDATE workspaces SET block_do_on_hold = true WHERE block_do_on_hold IS NULL"
    )
    op.execute(
        "UPDATE workspaces SET price_tolerance_percent = 2.00 WHERE price_tolerance_percent IS NULL"
    )

    # Make columns NOT NULL
    op.alter_column("workspaces", "credit_warning_days", nullable=False)
    op.alter_column("workspaces", "block_po_on_hold", nullable=False)
    op.alter_column("workspaces", "block_do_on_hold", nullable=False)
    op.alter_column("workspaces", "price_tolerance_percent", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workspaces", "price_tolerance_percent")
    op.drop_column("workspaces", "block_do_on_hold")
    op.drop_column("workspaces", "block_po_on_hold")
    op.drop_column("workspaces", "credit_warning_days")
    # ### end Alembic commands ###
