"""Add Wave 8 Procurement Requests

Revision ID: 0abb440e0fc9
Revises: d41016da5030
Create Date: 2026-08-19 20:05:17.408962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0abb440e0fc9'
down_revision: Union[str, None] = 'd41016da5030'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procurement_requests',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('request_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_type', sa.Enum('STOCK_REPLENISHMENT', 'CUSTOMER_ORDER', 'PROJECT', 'MANUAL', 'BACKORDER', 'INTERNAL_REQUIREMENT', name='prsourcetype'), nullable=False),
    sa.Column('destination_type', sa.Enum('WAREHOUSE', 'CUSTOMER', 'PROJECT', 'INTERNAL', 'UNALLOCATED', name='prdestinationtype'), nullable=False),
    sa.Column('customer_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('warehouse_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='prpriority'), nullable=False),
    sa.Column('procurement_method', sa.Enum('RFQ', 'DIRECT', 'CONTRACT', 'EMERGENCY', name='prmethod'), nullable=False),
    sa.Column('required_by_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'PARTIALLY_ORDERED', 'FULLY_ORDERED', 'FULFILLED', 'CANCELLED', name='prstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('requested_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'request_number', name='uq_workspace_pr_number')
    )
    op.create_index(op.f('ix_procurement_requests_request_number'), 'procurement_requests', ['request_number'], unique=False)
    op.create_index(op.f('ix_procurement_requests_workspace_id'), 'procurement_requests', ['workspace_id'], unique=False)
    op.create_table('procurement_request_items',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('request_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('product_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('uom_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('requested_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('approved_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ordered_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cancelled_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('received_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['procurement_requests.id'], ),
    sa.ForeignKeyConstraint(['uom_id'], ['units_of_measure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procurement_request_items_request_id'), 'procurement_request_items', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_procurement_request_items_request_id'), table_name='procurement_request_items')
    op.drop_table('procurement_request_items')
    op.drop_index(op.f('ix_procurement_requests_workspace_id'), table_name='procurement_requests')
    op.drop_index(op.f('ix_procurement_requests_request_number'), table_name='procurement_requests')
    op.drop_table('procurement_requests')
    # ### end Alembic commands ###
