"""baseline_v2

Revision ID: 13b9c7b44074
Revises: 001
Create Date: 2026-08-17 12:03:35.707416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '13b9c7b44074'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE invoiceeventtype AS ENUM ('INVOICE_CREATED', 'INVOICE_UPDATED', 'INVOICE_SENT', 'INVOICE_VIEWED', 'PAYMENT_ADDED', 'STATUS_CHANGED', 'INVOICE_VOIDED');")
    op.execute("CREATE TYPE invoicestatus AS ENUM ('DRAFT', 'SENT', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'CANCELLED');")
    op.execute("CREATE TYPE paymentgateway AS ENUM ('RAZORPAY', 'STRIPE', 'MANUAL');")
    op.execute("CREATE TYPE paymentstatus AS ENUM ('PENDING', 'SUCCESS', 'FAILED', 'CANCELLED', 'REFUNDED');")
    op.execute("CREATE TYPE userrole AS ENUM ('OWNER', 'ADMIN', 'MEMBER');")
    op.create_table('invoice_counters',
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('workspace_id', 'year')
    )
    op.create_table('idempotency_keys',
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('payment_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('workspace_id', 'key')
    )
    op.create_index(op.f('ix_idempotency_keys_payment_id'), 'idempotency_keys', ['payment_id'], unique=False)
    op.add_column('clients', sa.Column('tax_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('invoice_events', sa.Column('event_type', sa.Enum('INVOICE_CREATED', 'INVOICE_UPDATED', 'INVOICE_SENT', 'INVOICE_VIEWED', 'PAYMENT_ADDED', 'STATUS_CHANGED', 'INVOICE_VOIDED', name='invoiceeventtype'), nullable=False))
    op.execute("ALTER TABLE invoice_events ALTER COLUMN event_type TYPE invoiceeventtype USING event_type::text::invoiceeventtype")
    op.execute("ALTER TABLE invoices ALTER COLUMN status TYPE invoicestatus USING status::text::invoicestatus")
    op.create_index(op.f('ix_invoices_created_at'), 'invoices', ['created_at'], unique=False)
    op.execute("ALTER TABLE payments ALTER COLUMN gateway TYPE paymentgateway USING gateway::text::paymentgateway")
    op.execute("ALTER TABLE payments ALTER COLUMN status TYPE paymentstatus USING status::text::paymentstatus")
    op.execute("ALTER TABLE users ALTER COLUMN role TYPE userrole USING role::text::userrole")
    op.drop_index('ix_users_workspace_id', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_workspace_id', 'users', ['workspace_id'], unique=False)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='userrole'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('payments', 'status',
               existing_type=sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'CANCELLED', 'REFUNDED', name='paymentstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('payments', 'gateway',
               existing_type=sa.Enum('RAZORPAY', 'STRIPE', 'MANUAL', name='paymentgateway'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_index(op.f('ix_invoices_created_at'), table_name='invoices')
    op.alter_column('invoices', 'status',
               existing_type=sa.Enum('DRAFT', 'SENT', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'CANCELLED', name='invoicestatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('invoice_events', 'event_type')
    op.drop_column('clients', 'tax_id')
    op.drop_index(op.f('ix_idempotency_keys_payment_id'), table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_table('invoice_counters')
    # ### end Alembic commands ###
