"""Add Wave 11 GRN

Revision ID: 2a98d90a2f79
Revises: 345906985988
Create Date: 2026-08-19 21:08:34.560141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2a98d90a2f79'
down_revision: Union[str, None] = '345906985988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goods_receipt_notes',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('supplier_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('grn_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'RECEIVED', 'INSPECTED', 'POSTED', 'CANCELLED', name='grnstatus'), nullable=False),
    sa.Column('spo_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('warehouse_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('receipt_date', sa.Date(), nullable=False),
    sa.Column('supplier_delivery_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('received_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['received_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['spo_id'], ['supplier_purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'grn_number', name='uq_workspace_grn_number')
    )
    op.create_index(op.f('ix_goods_receipt_notes_grn_number'), 'goods_receipt_notes', ['grn_number'], unique=False)
    op.create_index(op.f('ix_goods_receipt_notes_supplier_id'), 'goods_receipt_notes', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_goods_receipt_notes_workspace_id'), 'goods_receipt_notes', ['workspace_id'], unique=False)
    op.create_table('grn_items',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('grn_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('product_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('spo_item_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('bin_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('quantity_received', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('quantity_accepted', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('quantity_rejected', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['bin_id'], ['warehouse_bins.id'], ),
    sa.ForeignKeyConstraint(['grn_id'], ['goods_receipt_notes.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['spo_item_id'], ['supplier_purchase_order_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grn_items_grn_id'), 'grn_items', ['grn_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grn_items_grn_id'), table_name='grn_items')
    op.drop_table('grn_items')
    op.drop_index(op.f('ix_goods_receipt_notes_workspace_id'), table_name='goods_receipt_notes')
    op.drop_index(op.f('ix_goods_receipt_notes_supplier_id'), table_name='goods_receipt_notes')
    op.drop_index(op.f('ix_goods_receipt_notes_grn_number'), table_name='goods_receipt_notes')
    op.drop_table('goods_receipt_notes')
    # ### end Alembic commands ###
