"""Add Wave 10 Supplier Purchase Orders

Revision ID: 345906985988
Revises: 64d6ac9e5b49
Create Date: 2026-08-19 20:43:24.533645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '345906985988'
down_revision: Union[str, None] = '64d6ac9e5b49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_purchase_orders',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('supplier_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('po_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ISSUED', 'ACKNOWLEDGED', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CANCELLED', name='spostatus'), nullable=False),
    sa.Column('award_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True),
    sa.Column('shipping_address', sa.Text(), nullable=True),
    sa.Column('billing_address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['award_id'], ['rfq_awards.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'po_number', name='uq_workspace_spo_number')
    )
    op.create_index(op.f('ix_supplier_purchase_orders_po_number'), 'supplier_purchase_orders', ['po_number'], unique=False)
    op.create_index(op.f('ix_supplier_purchase_orders_supplier_id'), 'supplier_purchase_orders', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_supplier_purchase_orders_workspace_id'), 'supplier_purchase_orders', ['workspace_id'], unique=False)
    op.create_table('supplier_purchase_order_items',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('spo_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('product_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('uom_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('award_line_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('received_quantity', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['award_line_id'], ['rfq_award_lines.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['spo_id'], ['supplier_purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['uom_id'], ['units_of_measure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_purchase_order_items_spo_id'), 'supplier_purchase_order_items', ['spo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplier_purchase_order_items_spo_id'), table_name='supplier_purchase_order_items')
    op.drop_table('supplier_purchase_order_items')
    op.drop_index(op.f('ix_supplier_purchase_orders_workspace_id'), table_name='supplier_purchase_orders')
    op.drop_index(op.f('ix_supplier_purchase_orders_supplier_id'), table_name='supplier_purchase_orders')
    op.drop_index(op.f('ix_supplier_purchase_orders_po_number'), table_name='supplier_purchase_orders')
    op.drop_table('supplier_purchase_orders')
    # ### end Alembic commands ###
