"""add grn models

Revision ID: 5f24e4eb1428
Revises: 63f069419100
Create Date: 2026-08-20 21:13:20.034900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5f24e4eb1428'
down_revision: Union[str, None] = '63f069419100'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### custom enum migration ###
    op.execute("ALTER TYPE grnstatus RENAME TO grnstatus_old")
    op.execute("CREATE TYPE grnstatus AS ENUM('DRAFT', 'RECEIVING', 'PENDING_INSPECTION', 'PARTIALLY_ACCEPTED', 'ACCEPTED', 'PARTIALLY_REJECTED', 'REJECTED', 'CANCELLED')")
    op.execute("ALTER TABLE goods_receipt_notes ALTER COLUMN status TYPE grnstatus USING status::text::grnstatus")
    op.execute("DROP TYPE grnstatus_old")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods_receipt_notes', sa.Column('received_date', sa.Date(), nullable=False))
    op.add_column('goods_receipt_notes', sa.Column('received_by', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.add_column('goods_receipt_notes', sa.Column('delivery_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('goods_receipt_notes', sa.Column('vehicle_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('goods_receipt_notes', sa.Column('driver_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('goods_receipt_notes', sa.Column('stock_posted', sa.Boolean(), nullable=False))
    op.alter_column('goods_receipt_notes', 'grn_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('uq_workspace_grn_number', 'goods_receipt_notes', type_='unique')
    op.create_index(op.f('ix_goods_receipt_notes_spo_id'), 'goods_receipt_notes', ['spo_id'], unique=False)
    op.create_index(op.f('ix_goods_receipt_notes_warehouse_id'), 'goods_receipt_notes', ['warehouse_id'], unique=False)
    op.create_unique_constraint('uq_grn_workspace_number', 'goods_receipt_notes', ['workspace_id', 'grn_number'])
    op.drop_constraint('goods_receipt_notes_received_by_id_fkey', 'goods_receipt_notes', type_='foreignkey')
    op.create_foreign_key(None, 'goods_receipt_notes', 'users', ['received_by'], ['id'])
    op.drop_column('goods_receipt_notes', 'receipt_date')
    op.drop_column('goods_receipt_notes', 'received_by_id')
    op.drop_column('goods_receipt_notes', 'supplier_delivery_note')
    op.add_column('grn_items', sa.Column('spo_delivery_schedule_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('grn_items', sa.Column('internal_sku', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('grn_items', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('grn_items', sa.Column('uom_id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.add_column('grn_items', sa.Column('location_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('grn_items', sa.Column('quantity_ordered_snapshot', sa.Numeric(precision=12, scale=4), nullable=False))
    op.add_column('grn_items', sa.Column('quantity_confirmed_snapshot', sa.Numeric(precision=12, scale=4), nullable=False))
    op.add_column('grn_items', sa.Column('quantity_damaged', sa.Numeric(precision=12, scale=4), nullable=False))
    op.add_column('grn_items', sa.Column('batch_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('grn_items', sa.Column('expiry_date', sa.Date(), nullable=True))
    op.add_column('grn_items', sa.Column('damage_reason', sa.Text(), nullable=True))
    op.add_column('grn_items', sa.Column('inspected_by', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('grn_items', sa.Column('inspected_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('grn_items', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('grn_items', 'spo_item_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('grn_items', 'quantity_received',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=12, scale=4),
               nullable=False)
    op.alter_column('grn_items', 'quantity_accepted',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=12, scale=4),
               nullable=False)
    op.alter_column('grn_items', 'quantity_rejected',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=12, scale=4),
               nullable=False)
    op.alter_column('grn_items', 'rejection_reason',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_grn_items_spo_item_id'), 'grn_items', ['spo_item_id'], unique=False)
    op.drop_constraint('grn_items_bin_id_fkey', 'grn_items', type_='foreignkey')
    op.create_foreign_key(None, 'grn_items', 'spo_delivery_schedules', ['spo_delivery_schedule_id'], ['id'])
    op.create_foreign_key(None, 'grn_items', 'users', ['inspected_by'], ['id'])
    op.create_foreign_key(None, 'grn_items', 'units_of_measure', ['uom_id'], ['id'])
    op.drop_column('grn_items', 'bin_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grn_items', sa.Column('bin_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'grn_items', type_='foreignkey')
    op.drop_constraint(None, 'grn_items', type_='foreignkey')
    op.drop_constraint(None, 'grn_items', type_='foreignkey')
    op.create_foreign_key('grn_items_bin_id_fkey', 'grn_items', 'warehouse_bins', ['bin_id'], ['id'])
    op.drop_index(op.f('ix_grn_items_spo_item_id'), table_name='grn_items')
    op.alter_column('grn_items', 'rejection_reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('grn_items', 'quantity_rejected',
               existing_type=sa.Numeric(precision=12, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('grn_items', 'quantity_accepted',
               existing_type=sa.Numeric(precision=12, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('grn_items', 'quantity_received',
               existing_type=sa.Numeric(precision=12, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('grn_items', 'spo_item_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('grn_items', 'notes')
    op.drop_column('grn_items', 'inspected_at')
    op.drop_column('grn_items', 'inspected_by')
    op.drop_column('grn_items', 'damage_reason')
    op.drop_column('grn_items', 'expiry_date')
    op.drop_column('grn_items', 'batch_number')
    op.drop_column('grn_items', 'quantity_damaged')
    op.drop_column('grn_items', 'quantity_confirmed_snapshot')
    op.drop_column('grn_items', 'quantity_ordered_snapshot')
    op.drop_column('grn_items', 'location_id')
    op.drop_column('grn_items', 'uom_id')
    op.drop_column('grn_items', 'description')
    op.drop_column('grn_items', 'internal_sku')
    op.drop_column('grn_items', 'spo_delivery_schedule_id')
    op.add_column('goods_receipt_notes', sa.Column('supplier_delivery_note', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('goods_receipt_notes', sa.Column('received_by_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('goods_receipt_notes', sa.Column('receipt_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'goods_receipt_notes', type_='foreignkey')
    op.create_foreign_key('goods_receipt_notes_received_by_id_fkey', 'goods_receipt_notes', 'users', ['received_by_id'], ['id'])
    op.drop_constraint('uq_grn_workspace_number', 'goods_receipt_notes', type_='unique')
    op.drop_index(op.f('ix_goods_receipt_notes_warehouse_id'), table_name='goods_receipt_notes')
    op.drop_index(op.f('ix_goods_receipt_notes_spo_id'), table_name='goods_receipt_notes')
    op.create_unique_constraint('uq_workspace_grn_number', 'goods_receipt_notes', ['workspace_id', 'grn_number'])
    op.alter_column('goods_receipt_notes', 'grn_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('goods_receipt_notes', 'stock_posted')
    op.drop_column('goods_receipt_notes', 'driver_name')
    op.drop_column('goods_receipt_notes', 'vehicle_number')
    op.drop_column('goods_receipt_notes', 'delivery_reference')
    op.drop_column('goods_receipt_notes', 'received_by')
    op.drop_column('goods_receipt_notes', 'received_date')
    # ### end Alembic commands ###
