"""add supplier invoice models

Revision ID: 633b2df1fb55
Revises: 5f24e4eb1428
Create Date: 2026-08-23 13:49:16.737919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '633b2df1fb55'
down_revision: Union[str, None] = '5f24e4eb1428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_invoices',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('supplier_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('supplier_invoice_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('our_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('invoice_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('discount_amount', sa.Float(), nullable=False),
    sa.Column('vat_amount', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('balance_due', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'PENDING_MATCHING', 'MATCHED', 'DISCREPANCY', 'APPROVED', 'PARTIALLY_PAID', 'PAID', 'CANCELLED', name='supplierinvoicestatus'), nullable=False),
    sa.Column('three_way_match_status', sa.Enum('NOT_CHECKED', 'PASSED', 'FAILED_QTY', 'FAILED_PRICE', 'FAILED_TAX', 'FAILED_SUPPLIER', 'FAILED_CURRENCY', 'FAILED_PRODUCT', 'FAILED_UOM', 'DUPLICATE_INVOICE', 'UNRECEIVED_ITEMS', 'MANUAL_REVIEW', name='matchresult'), nullable=False),
    sa.Column('three_way_match_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('document_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ocr_job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ocr_extracted', sa.Boolean(), nullable=False),
    sa.Column('primary_spo_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['primary_spo_id'], ['supplier_purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'supplier_id', 'supplier_invoice_number', name='uq_workspace_supplier_invoice_num')
    )
    op.create_index(op.f('ix_supplier_invoices_supplier_id'), 'supplier_invoices', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_supplier_invoices_supplier_invoice_number'), 'supplier_invoices', ['supplier_invoice_number'], unique=False)
    op.create_index(op.f('ix_supplier_invoices_workspace_id'), 'supplier_invoices', ['workspace_id'], unique=False)
    op.create_table('supplier_invoice_items',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('supplier_invoice_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('spo_item_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('grn_item_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('product_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('uom_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('discount_percent', sa.Float(), nullable=False),
    sa.Column('vat_rate', sa.Float(), nullable=False),
    sa.Column('vat_amount', sa.Float(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('match_status', sa.Enum('NOT_CHECKED', 'PASSED', 'FAILED_QTY', 'FAILED_PRICE', 'FAILED_TAX', 'FAILED_SUPPLIER', 'FAILED_CURRENCY', 'FAILED_PRODUCT', 'FAILED_UOM', 'DUPLICATE_INVOICE', 'UNRECEIVED_ITEMS', 'MANUAL_REVIEW', name='matchresult'), nullable=False),
    sa.Column('variance_quantity', sa.Float(), nullable=False),
    sa.Column('variance_price', sa.Float(), nullable=False),
    sa.Column('variance_tax', sa.Float(), nullable=False),
    sa.Column('variance_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['grn_item_id'], ['grn_items.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['spo_item_id'], ['supplier_purchase_order_items.id'], ),
    sa.ForeignKeyConstraint(['supplier_invoice_id'], ['supplier_invoices.id'], ),
    sa.ForeignKeyConstraint(['uom_id'], ['units_of_measure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_invoice_items_supplier_invoice_id'), 'supplier_invoice_items', ['supplier_invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplier_invoice_items_supplier_invoice_id'), table_name='supplier_invoice_items')
    op.drop_table('supplier_invoice_items')
    op.drop_index(op.f('ix_supplier_invoices_workspace_id'), table_name='supplier_invoices')
    op.drop_index(op.f('ix_supplier_invoices_supplier_invoice_number'), table_name='supplier_invoices')
    op.drop_index(op.f('ix_supplier_invoices_supplier_id'), table_name='supplier_invoices')
    op.drop_table('supplier_invoices')
    # ### end Alembic commands ###
