"""add spo architecture

Revision ID: 63f069419100
Revises: 2a98d90a2f79
Create Date: 2026-08-20 19:48:37.518925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '63f069419100'
down_revision: Union[str, None] = '2a98d90a2f79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE TABLE supplier_purchase_orders CASCADE")
    op.create_table('spo_amendments',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('spo_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('amendment_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'PENDING_APPROVAL', 'APPROVED', 'SUPPLIER_REJECTED', 'APPLIED', 'WITHDRAWN', name='spoamendmentstatus'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('requires_supplier_reconfirmation', sa.Boolean(), nullable=False),
    sa.Column('amended_by', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('approved_by', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['amended_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['spo_id'], ['supplier_purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spo_amendments_spo_id'), 'spo_amendments', ['spo_id'], unique=False)
    op.create_table('spo_status_history',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('spo_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('from_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('to_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('triggered_by', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('trigger_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['spo_id'], ['supplier_purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spo_status_history_spo_id'), 'spo_status_history', ['spo_id'], unique=False)
    op.create_table('spo_amendment_lines',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('amendment_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('spo_item_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('field_name', sa.Enum('QUANTITY_ORDERED', 'UNIT_PRICE', 'DELIVERY_DATE', 'DELIVERY_TERMS', 'OTHER', name='spoamendmentfield'), nullable=False),
    sa.Column('old_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('new_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['amendment_id'], ['spo_amendments.id'], ),
    sa.ForeignKeyConstraint(['spo_item_id'], ['supplier_purchase_order_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spo_amendment_lines_amendment_id'), 'spo_amendment_lines', ['amendment_id'], unique=False)
    op.create_table('spo_delivery_schedules',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('spo_item_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('tranche_number', sa.Integer(), nullable=False),
    sa.Column('scheduled_quantity', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_TRANSIT', 'DELIVERED', 'DELAYED', 'CANCELLED', name='spodeliveryschedulestatus'), nullable=False),
    sa.Column('delayed_flagged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['spo_item_id'], ['supplier_purchase_order_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spo_delivery_schedules_spo_item_id'), 'spo_delivery_schedules', ['spo_item_id'], unique=False)
    op.add_column('supplier_purchase_order_items', sa.Column('line_number', sa.Integer(), server_default='1', nullable=False))
    op.add_column('supplier_purchase_order_items', sa.Column('rfq_award_line_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('supplier_purchase_order_items', sa.Column('procurement_request_item_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('supplier_purchase_order_items', sa.Column('internal_sku', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('supplier_purchase_order_items', sa.Column('supplier_sku', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('supplier_purchase_order_items', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), server_default='', nullable=False))
    op.add_column('supplier_purchase_order_items', sa.Column('quantity_ordered', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('supplier_purchase_order_items', sa.Column('quantity_confirmed', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('supplier_purchase_order_items', sa.Column('quantity_backordered', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('supplier_purchase_order_items', sa.Column('quantity_received', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('supplier_purchase_order_items', sa.Column('quantity_accepted', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('supplier_purchase_order_items', sa.Column('quantity_damaged_rejected', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('supplier_purchase_order_items', sa.Column('quantity_invoiced', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('supplier_purchase_order_items', sa.Column('quantity_cancelled', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('supplier_purchase_order_items', sa.Column('open_quantity', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('supplier_purchase_order_items', sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('supplier_purchase_order_items', sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('supplier_purchase_order_items', sa.Column('vat_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('supplier_purchase_order_items', sa.Column('price_amendment_pending', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('supplier_purchase_order_items', sa.Column('expected_delivery_date', sa.Date(), nullable=True))
    op.alter_column('supplier_purchase_order_items', 'unit_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('supplier_purchase_order_items', 'total_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.drop_constraint('supplier_purchase_order_items_award_line_id_fkey', 'supplier_purchase_order_items', type_='foreignkey')
    op.create_foreign_key(None, 'supplier_purchase_order_items', 'procurement_request_items', ['procurement_request_item_id'], ['id'])
    op.create_foreign_key(None, 'supplier_purchase_order_items', 'rfq_award_lines', ['rfq_award_line_id'], ['id'])
    op.drop_column('supplier_purchase_order_items', 'received_quantity')
    op.drop_column('supplier_purchase_order_items', 'discount_percentage')
    op.drop_column('supplier_purchase_order_items', 'award_line_id')
    op.drop_column('supplier_purchase_order_items', 'tax_rate')
    op.drop_column('supplier_purchase_order_items', 'quantity')
    op.add_column('supplier_purchase_orders', sa.Column('spo_number', sqlmodel.sql.sqltypes.AutoString(), server_default='0', nullable=False))
    op.add_column('supplier_purchase_orders', sa.Column('rfq_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('supplier_purchase_orders', sa.Column('procurement_request_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    procurementmethod = sa.Enum('RFQ', 'DIRECT', 'CONTRACT', 'EMERGENCY', name='procurementmethod')
    procurementmethod.create(op.get_bind(), checkfirst=True)
    op.add_column('supplier_purchase_orders', sa.Column('procurement_method', procurementmethod, server_default='RFQ', nullable=False))
    op.add_column('supplier_purchase_orders', sa.Column('single_source_justification', sa.Text(), nullable=True))
    op.add_column('supplier_purchase_orders', sa.Column('supplier_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('supplier_purchase_orders', sa.Column('po_date', sa.Date(), nullable=True))
    op.add_column('supplier_purchase_orders', sa.Column('warehouse_id', sqlmodel.sql.sqltypes.GUID(), server_default='00000000-0000-0000-0000-000000000000', nullable=False))
    op.add_column('supplier_purchase_orders', sa.Column('payment_terms_days', sa.Integer(), server_default='0', nullable=False))
    op.add_column('supplier_purchase_orders', sa.Column('delivery_terms', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('supplier_purchase_orders', sa.Column('vat_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('supplier_purchase_orders', sa.Column('quantity_ordered_total', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('supplier_purchase_orders', sa.Column('quantity_confirmed_total', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('supplier_purchase_orders', sa.Column('quantity_backordered_total', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('supplier_purchase_orders', sa.Column('has_open_amendment', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('supplier_purchase_orders', sa.Column('approved_by', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('supplier_purchase_orders', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('supplier_purchase_orders', sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('supplier_purchase_orders', sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('supplier_purchase_orders', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_supplier_purchase_orders_po_number', table_name='supplier_purchase_orders')
    op.drop_constraint('uq_workspace_spo_number', 'supplier_purchase_orders', type_='unique')
    op.create_unique_constraint('uq_workspace_spo_number', 'supplier_purchase_orders', ['workspace_id', 'spo_number'])
    op.create_index(op.f('ix_supplier_purchase_orders_spo_number'), 'supplier_purchase_orders', ['spo_number'], unique=False)
    op.drop_constraint('supplier_purchase_orders_award_id_fkey', 'supplier_purchase_orders', type_='foreignkey')
    op.drop_constraint('supplier_purchase_orders_created_by_id_fkey', 'supplier_purchase_orders', type_='foreignkey')
    op.create_foreign_key(None, 'supplier_purchase_orders', 'procurement_requests', ['procurement_request_id'], ['id'])
    op.create_foreign_key(None, 'supplier_purchase_orders', 'rfqs', ['rfq_id'], ['id'])
    op.create_foreign_key(None, 'supplier_purchase_orders', 'warehouses', ['warehouse_id'], ['id'])
    op.create_foreign_key(None, 'supplier_purchase_orders', 'users', ['approved_by'], ['id'])
    op.drop_column('supplier_purchase_orders', 'created_by_id')
    op.drop_column('supplier_purchase_orders', 'billing_address')
    op.drop_column('supplier_purchase_orders', 'shipping_address')
    op.drop_column('supplier_purchase_orders', 'terms')
    op.drop_column('supplier_purchase_orders', 'po_number')
    op.drop_column('supplier_purchase_orders', 'exchange_rate')
    op.drop_column('supplier_purchase_orders', 'award_id')
    op.drop_column('supplier_purchase_orders', 'tax_amount')
    op.drop_column('supplier_purchase_orders', 'notes')
    op.add_column('workspaces', sa.Column('over_receipt_tolerance_percent', sa.Numeric(precision=5, scale=2), server_default='2.00', nullable=False))
    op.add_column('workspaces', sa.Column('spo_amendment_approval_threshold', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'spo_amendment_approval_threshold')
    op.drop_column('workspaces', 'over_receipt_tolerance_percent')
    op.add_column('supplier_purchase_orders', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('supplier_purchase_orders', sa.Column('tax_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('supplier_purchase_orders', sa.Column('award_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('supplier_purchase_orders', sa.Column('exchange_rate', sa.NUMERIC(precision=12, scale=6), autoincrement=False, nullable=True))
    op.add_column('supplier_purchase_orders', sa.Column('po_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('supplier_purchase_orders', sa.Column('terms', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('supplier_purchase_orders', sa.Column('shipping_address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('supplier_purchase_orders', sa.Column('billing_address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('supplier_purchase_orders', sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'supplier_purchase_orders', type_='foreignkey')
    op.drop_constraint(None, 'supplier_purchase_orders', type_='foreignkey')
    op.drop_constraint(None, 'supplier_purchase_orders', type_='foreignkey')
    op.drop_constraint(None, 'supplier_purchase_orders', type_='foreignkey')
    op.create_foreign_key('supplier_purchase_orders_created_by_id_fkey', 'supplier_purchase_orders', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key('supplier_purchase_orders_award_id_fkey', 'supplier_purchase_orders', 'rfq_awards', ['award_id'], ['id'])
    op.drop_index(op.f('ix_supplier_purchase_orders_spo_number'), table_name='supplier_purchase_orders')
    op.drop_constraint('uq_workspace_spo_number', 'supplier_purchase_orders', type_='unique')
    op.create_unique_constraint('uq_workspace_spo_number', 'supplier_purchase_orders', ['workspace_id', 'po_number'])
    op.create_index('ix_supplier_purchase_orders_po_number', 'supplier_purchase_orders', ['po_number'], unique=False)
    op.drop_column('supplier_purchase_orders', 'closed_at')
    op.drop_column('supplier_purchase_orders', 'acknowledged_at')
    op.drop_column('supplier_purchase_orders', 'sent_at')
    op.drop_column('supplier_purchase_orders', 'approved_at')
    op.drop_column('supplier_purchase_orders', 'approved_by')
    op.drop_column('supplier_purchase_orders', 'has_open_amendment')
    op.drop_column('supplier_purchase_orders', 'quantity_backordered_total')
    op.drop_column('supplier_purchase_orders', 'quantity_confirmed_total')
    op.drop_column('supplier_purchase_orders', 'quantity_ordered_total')
    op.drop_column('supplier_purchase_orders', 'vat_amount')
    op.drop_column('supplier_purchase_orders', 'delivery_terms')
    op.drop_column('supplier_purchase_orders', 'payment_terms_days')
    op.drop_column('supplier_purchase_orders', 'warehouse_id')
    op.drop_column('supplier_purchase_orders', 'po_date')
    op.drop_column('supplier_purchase_orders', 'supplier_reference')
    op.drop_column('supplier_purchase_orders', 'single_source_justification')
    op.drop_column('supplier_purchase_orders', 'procurement_method')
    op.drop_column('supplier_purchase_orders', 'procurement_request_id')
    op.drop_column('supplier_purchase_orders', 'rfq_id')
    op.drop_column('supplier_purchase_orders', 'spo_number')
    op.add_column('supplier_purchase_order_items', sa.Column('quantity', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('supplier_purchase_order_items', sa.Column('tax_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('supplier_purchase_order_items', sa.Column('award_line_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('supplier_purchase_order_items', sa.Column('discount_percentage', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('supplier_purchase_order_items', sa.Column('received_quantity', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'supplier_purchase_order_items', type_='foreignkey')
    op.drop_constraint(None, 'supplier_purchase_order_items', type_='foreignkey')
    op.create_foreign_key('supplier_purchase_order_items_award_line_id_fkey', 'supplier_purchase_order_items', 'rfq_award_lines', ['award_line_id'], ['id'])
    op.alter_column('supplier_purchase_order_items', 'total_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('supplier_purchase_order_items', 'unit_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.drop_column('supplier_purchase_order_items', 'expected_delivery_date')
    op.drop_column('supplier_purchase_order_items', 'price_amendment_pending')
    op.drop_column('supplier_purchase_order_items', 'vat_amount')
    op.drop_column('supplier_purchase_order_items', 'vat_rate')
    op.drop_column('supplier_purchase_order_items', 'discount_percent')
    op.drop_column('supplier_purchase_order_items', 'open_quantity')
    op.drop_column('supplier_purchase_order_items', 'quantity_cancelled')
    op.drop_column('supplier_purchase_order_items', 'quantity_invoiced')
    op.drop_column('supplier_purchase_order_items', 'quantity_damaged_rejected')
    op.drop_column('supplier_purchase_order_items', 'quantity_accepted')
    op.drop_column('supplier_purchase_order_items', 'quantity_received')
    op.drop_column('supplier_purchase_order_items', 'quantity_backordered')
    op.drop_column('supplier_purchase_order_items', 'quantity_confirmed')
    op.drop_column('supplier_purchase_order_items', 'quantity_ordered')
    op.drop_column('supplier_purchase_order_items', 'description')
    op.drop_column('supplier_purchase_order_items', 'supplier_sku')
    op.drop_column('supplier_purchase_order_items', 'internal_sku')
    op.drop_column('supplier_purchase_order_items', 'procurement_request_item_id')
    op.drop_column('supplier_purchase_order_items', 'rfq_award_line_id')
    op.drop_column('supplier_purchase_order_items', 'line_number')
    op.drop_index(op.f('ix_spo_delivery_schedules_spo_item_id'), table_name='spo_delivery_schedules')
    op.drop_table('spo_delivery_schedules')
    op.drop_index(op.f('ix_spo_amendment_lines_amendment_id'), table_name='spo_amendment_lines')
    op.drop_table('spo_amendment_lines')
    op.drop_index(op.f('ix_spo_status_history_spo_id'), table_name='spo_status_history')
    op.drop_table('spo_status_history')
    op.drop_index(op.f('ix_spo_amendments_spo_id'), table_name='spo_amendments')
    op.drop_table('spo_amendments')
    # ### end Alembic commands ###
