"""Add Wave 9 RFQ Master

Revision ID: 64d6ac9e5b49
Revises: 0abb440e0fc9
Create Date: 2026-08-19 20:10:39.447959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '64d6ac9e5b49'
down_revision: Union[str, None] = '0abb440e0fc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rfqs',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('rfq_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rfq_type', sa.Enum('STANDARD', 'URGENT', 'MARKET_DISCOVERY', 'ANNUAL_CONTRACT', name='rfqtype'), nullable=False),
    sa.Column('award_mode', sa.Enum('SINGLE', 'SPLIT', name='rfqawardmode'), nullable=False),
    sa.Column('evaluation_criteria', sa.Enum('LOWEST_PRICE', 'LOWEST_LANDED_COST', 'WEIGHTED_SCORE', name='rfqevalcriteria'), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sealed_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'PARTIALLY_RESPONDED', 'FULLY_RESPONDED', 'UNDER_EVALUATION', 'PARTIALLY_AWARDED', 'AWARDED', 'EXPIRED', name='rfqstatus'), nullable=False),
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'rfq_number', name='uq_workspace_rfq_number')
    )
    op.create_index(op.f('ix_rfqs_rfq_number'), 'rfqs', ['rfq_number'], unique=False)
    op.create_index(op.f('ix_rfqs_workspace_id'), 'rfqs', ['workspace_id'], unique=False)
    op.create_table('rfq_awards',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('rfq_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('supplier_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('award_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_awarded_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'CONVERTED', name='awardstatus'), nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'award_number', name='uq_workspace_award_number')
    )
    op.create_index(op.f('ix_rfq_awards_award_number'), 'rfq_awards', ['award_number'], unique=False)
    op.create_index(op.f('ix_rfq_awards_workspace_id'), 'rfq_awards', ['workspace_id'], unique=False)
    op.create_table('rfq_items',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('rfq_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('product_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('uom_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.Column('awarded_quantity', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.ForeignKeyConstraint(['uom_id'], ['units_of_measure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfq_items_rfq_id'), 'rfq_items', ['rfq_id'], unique=False)
    op.create_table('supplier_rfq_responses',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('rfq_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('supplier_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RECEIVED', 'SHORTLISTED', 'SELECTED', 'PARTIALLY_SELECTED', 'NOT_SELECTED', 'DECLINED', 'NO_RESPONSE', 'WITHDRAWN', 'SUPERSEDED', name='quotestatus'), nullable=False),
    sa.Column('completeness', sa.Enum('FULL', 'PARTIAL', 'INCOMPLETE', name='quotecompleteness'), nullable=False),
    sa.Column('quote_currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('normalized_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rfq_id', 'supplier_id', 'revision_number', name='uq_rfq_supplier_revision')
    )
    op.create_index(op.f('ix_supplier_rfq_responses_rfq_id'), 'supplier_rfq_responses', ['rfq_id'], unique=False)
    op.create_table('rfq_item_sources',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('rfq_item_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('procurement_request_item_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('quantity_from_source', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['procurement_request_item_id'], ['procurement_request_items.id'], ),
    sa.ForeignKeyConstraint(['rfq_item_id'], ['rfq_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfq_item_sources_rfq_item_id'), 'rfq_item_sources', ['rfq_item_id'], unique=False)
    op.create_table('supplier_quote_items',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('response_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('rfq_item_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('is_alternate', sa.Boolean(), nullable=True),
    sa.Column('alternate_product_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('quantity_available', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('quoted_unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('normalized_unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['alternate_product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['response_id'], ['supplier_rfq_responses.id'], ),
    sa.ForeignKeyConstraint(['rfq_item_id'], ['rfq_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_quote_items_response_id'), 'supplier_quote_items', ['response_id'], unique=False)
    op.create_table('rfq_award_lines',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('award_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('quote_item_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('awarded_quantity', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_lowest_price', sa.Boolean(), nullable=True),
    sa.Column('deviation_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['award_id'], ['rfq_awards.id'], ),
    sa.ForeignKeyConstraint(['quote_item_id'], ['supplier_quote_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfq_award_lines_award_id'), 'rfq_award_lines', ['award_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rfq_award_lines_award_id'), table_name='rfq_award_lines')
    op.drop_table('rfq_award_lines')
    op.drop_index(op.f('ix_supplier_quote_items_response_id'), table_name='supplier_quote_items')
    op.drop_table('supplier_quote_items')
    op.drop_index(op.f('ix_rfq_item_sources_rfq_item_id'), table_name='rfq_item_sources')
    op.drop_table('rfq_item_sources')
    op.drop_index(op.f('ix_supplier_rfq_responses_rfq_id'), table_name='supplier_rfq_responses')
    op.drop_table('supplier_rfq_responses')
    op.drop_index(op.f('ix_rfq_items_rfq_id'), table_name='rfq_items')
    op.drop_table('rfq_items')
    op.drop_index(op.f('ix_rfq_awards_workspace_id'), table_name='rfq_awards')
    op.drop_index(op.f('ix_rfq_awards_award_number'), table_name='rfq_awards')
    op.drop_table('rfq_awards')
    op.drop_index(op.f('ix_rfqs_workspace_id'), table_name='rfqs')
    op.drop_index(op.f('ix_rfqs_rfq_number'), table_name='rfqs')
    op.drop_table('rfqs')
    # ### end Alembic commands ###
