"""rfq_award_flow_counters_threshold_attribution

Revision ID: 6d27f753e9e3
Revises: 985774b20cc8
Create Date: 2026-09-13 10:09:03.920687

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "6d27f753e9e3"
down_revision: Union[str, None] = "985774b20cc8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rfq_award_counters",
        sa.Column("workspace_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("last_number", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("workspace_id", "year"),
    )
    op.add_column(
        "rfq_awards",
        sa.Column("awarded_by", sqlmodel.sql.sqltypes.GUID(), nullable=True),
    )
    op.add_column(
        "rfq_awards",
        sa.Column("approved_by", sqlmodel.sql.sqltypes.GUID(), nullable=True),
    )
    op.create_foreign_key(
        "fk_rfq_awards_awarded_by", "rfq_awards", "users", ["awarded_by"], ["id"]
    )
    op.create_foreign_key(
        "fk_rfq_awards_approved_by", "rfq_awards", "users", ["approved_by"], ["id"]
    )
    op.add_column(
        "supplier_quote_items",
        sa.Column("uom_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
    )
    op.create_foreign_key(
        "fk_supplier_quote_items_uom_id",
        "supplier_quote_items",
        "units_of_measure",
        ["uom_id"],
        ["id"],
    )
    op.add_column(
        "workspaces",
        sa.Column(
            "rfq_award_approval_threshold",
            sa.Numeric(precision=12, scale=2),
            server_default="0.00",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workspaces", "rfq_award_approval_threshold")
    op.drop_constraint(
        "fk_supplier_quote_items_uom_id", "supplier_quote_items", type_="foreignkey"
    )
    op.drop_column("supplier_quote_items", "uom_id")
    op.drop_constraint("fk_rfq_awards_approved_by", "rfq_awards", type_="foreignkey")
    op.drop_constraint("fk_rfq_awards_awarded_by", "rfq_awards", type_="foreignkey")
    op.drop_column("rfq_awards", "approved_by")
    op.drop_column("rfq_awards", "awarded_by")
    op.drop_table("rfq_award_counters")
    # ### end Alembic commands ###
