"""Add Wave 2 workspace settings

Revision ID: 96b45ccabfb7
Revises: 4ec511b03a6f
Create Date: 2026-08-19 16:23:14.424116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '96b45ccabfb7'
down_revision: Union[str, None] = '4ec511b03a6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('trn', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('workspaces', sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('workspaces', sa.Column('whatsapp_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('workspaces', sa.Column('default_tax_rate', sa.Numeric(precision=5, scale=2), nullable=False))
    op.add_column('workspaces', sa.Column('credit_limit_default', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('workspaces', sa.Column('credit_hold_days', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'credit_hold_days')
    op.drop_column('workspaces', 'credit_limit_default')
    op.drop_column('workspaces', 'default_tax_rate')
    op.drop_column('workspaces', 'whatsapp_number')
    op.drop_column('workspaces', 'logo_url')
    op.drop_column('workspaces', 'trn')
    # ### end Alembic commands ###
