"""supplier_invoice_events

Revision ID: 9788f2686209
Revises: 6d27f753e9e3
Create Date: 2026-09-13 12:32:22.856578

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9788f2686209"
down_revision: Union[str, None] = "6d27f753e9e3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "supplier_invoice_events",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("supplier_invoice_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("workspace_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "CREATED",
                "MATCH_SUBMITTED",
                "MATCHED",
                "DISCREPANCY",
                "DISCREPANCY_RESOLVED",
                "APPROVED",
                "PARTIALLY_PAID",
                "PAID",
                "PAYMENT_REVERSED",
                "DEBIT_NOTE_APPLIED",
                name="supplierinvoiceeventtype",
            ),
            nullable=False,
        ),
        sa.Column("previous_status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("new_status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("actor_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column(
            "metadata_log", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_invoice_id"],
            ["supplier_invoices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_supplier_invoice_events_supplier_invoice_id"),
        "supplier_invoice_events",
        ["supplier_invoice_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_supplier_invoice_events_workspace_id"),
        "supplier_invoice_events",
        ["workspace_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_supplier_invoice_events_workspace_id"),
        table_name="supplier_invoice_events",
    )
    op.drop_index(
        op.f("ix_supplier_invoice_events_supplier_invoice_id"),
        table_name="supplier_invoice_events",
    )
    op.drop_table("supplier_invoice_events")
    postgresql.ENUM(name="supplierinvoiceeventtype").drop(
        op.get_bind(), checkfirst=True
    )
    # ### end Alembic commands ###
