"""add_d22_landed_cost_allocations

Revision ID: 985774b20cc8
Revises: e1f0aabb01aa
Create Date: 2026-09-12 21:36:30.269977

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "985774b20cc8"
down_revision: Union[str, None] = "e1f0aabb01aa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "landed_cost_allocations",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("workspace_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("grn_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("grn_item_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("spo_item_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("component_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "allocation_basis", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "allocation_factor", sa.Numeric(precision=14, scale=6), nullable=True
        ),
        sa.Column(
            "source_document_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("source_document_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column("source_line_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("allocated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("capitalized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["grn_id"],
            ["goods_receipt_notes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["grn_item_id"],
            ["grn_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["spo_item_id"],
            ["supplier_purchase_order_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workspace_id",
            "source_document_type",
            "source_document_id",
            "source_line_id",
            name="uq_landed_cost_source",
        ),
    )
    op.create_index(
        op.f("ix_landed_cost_allocations_grn_id"),
        "landed_cost_allocations",
        ["grn_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_landed_cost_allocations_grn_item_id"),
        "landed_cost_allocations",
        ["grn_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_landed_cost_allocations_spo_item_id"),
        "landed_cost_allocations",
        ["spo_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_landed_cost_allocations_workspace_id"),
        "landed_cost_allocations",
        ["workspace_id"],
        unique=False,
    )
    op.add_column(
        "grn_items",
        sa.Column(
            "landed_cost_allocated",
            sa.Numeric(precision=12, scale=2),
            server_default="0.00",
            nullable=False,
        ),
    )
    op.add_column(
        "grn_items",
        sa.Column(
            "landed_cost_per_unit",
            sa.Numeric(precision=12, scale=4),
            server_default="0.0000",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("grn_items", "landed_cost_per_unit")
    op.drop_column("grn_items", "landed_cost_allocated")
    op.drop_index(
        op.f("ix_landed_cost_allocations_workspace_id"),
        table_name="landed_cost_allocations",
    )
    op.drop_index(
        op.f("ix_landed_cost_allocations_spo_item_id"),
        table_name="landed_cost_allocations",
    )
    op.drop_index(
        op.f("ix_landed_cost_allocations_grn_item_id"),
        table_name="landed_cost_allocations",
    )
    op.drop_index(
        op.f("ix_landed_cost_allocations_grn_id"), table_name="landed_cost_allocations"
    )
    op.drop_table("landed_cost_allocations")
    # ### end Alembic commands ###
