"""fix supplier_id fk

Revision ID: 9ab488fc07a8
Revises: 633b2df1fb55
Create Date: 2026-08-23 14:25:12.829869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ab488fc07a8'
down_revision: Union[str, None] = '633b2df1fb55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('supplier_invoices_supplier_id_fkey', 'supplier_invoices', type_='foreignkey')
    op.create_foreign_key(None, 'supplier_invoices', 'suppliers', ['supplier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'supplier_invoices', type_='foreignkey')
    op.create_foreign_key('supplier_invoices_supplier_id_fkey', 'supplier_invoices', 'clients', ['supplier_id'], ['id'])
    # ### end Alembic commands ###
