"""add purchase return vat fields

Revision ID: a092180229a7
Revises: 9788f2686209
Create Date: 2026-09-14 13:34:01.480695

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a092180229a7"
down_revision: Union[str, None] = "9788f2686209"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "purchase_return_items",
        sa.Column("vat_rate", sa.Numeric(precision=5, scale=2), nullable=False),
    )
    op.add_column(
        "purchase_return_items",
        sa.Column("vat_amount", sa.Numeric(precision=12, scale=2), nullable=False),
    )
    op.add_column(
        "supplier_debit_notes",
        sa.Column("subtotal", sa.Numeric(precision=12, scale=2), nullable=False),
    )
    op.add_column(
        "supplier_debit_notes",
        sa.Column("vat_amount", sa.Numeric(precision=12, scale=2), nullable=False),
    )
    op.add_column(
        "supplier_debit_notes",
        sa.Column("total_amount", sa.Numeric(precision=12, scale=2), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("supplier_debit_notes", "total_amount")
    op.drop_column("supplier_debit_notes", "vat_amount")
    op.drop_column("supplier_debit_notes", "subtotal")
    op.drop_column("purchase_return_items", "vat_amount")
    op.drop_column("purchase_return_items", "vat_rate")
    # ### end Alembic commands ###
