"""add purchase return receipt workflow

Revision ID: b8f90cbf88f6
Revises: a092180229a7
Create Date: 2026-09-14 17:01:51.746737

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "b8f90cbf88f6"
down_revision: Union[str, None] = "a092180229a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add RECEIVED_BACK enum value to purchasereturnstatus (idempotent)
    op.execute(
        "ALTER TYPE purchasereturnstatus ADD VALUE IF NOT EXISTS 'RECEIVED_BACK'"
    )

    op.create_table(
        "purchase_return_receipt_counters",
        sa.Column("workspace_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("last_number", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("workspace_id", "year"),
    )
    op.create_table(
        "purchase_return_receipts",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("workspace_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("purchase_return_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("warehouse_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("bin_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column("receipt_number", sa.Text(), nullable=False),
        sa.Column("receipt_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "RECEIVING",
                "RECEIVED",
                "CANCELLED",
                name="purchasereturnreceiptstatus",
            ),
            nullable=False,
        ),
        sa.Column("received_by", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["bin_id"],
            ["warehouse_bins.id"],
        ),
        sa.ForeignKeyConstraint(
            ["purchase_return_id"],
            ["purchase_returns.id"],
        ),
        sa.ForeignKeyConstraint(
            ["received_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workspace_id",
            "receipt_number",
            name="uq_purchase_return_receipt_workspace_number",
        ),
    )
    op.create_index(
        op.f("ix_purchase_return_receipts_bin_id"),
        "purchase_return_receipts",
        ["bin_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_purchase_return_receipts_purchase_return_id"),
        "purchase_return_receipts",
        ["purchase_return_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_purchase_return_receipts_receipt_number"),
        "purchase_return_receipts",
        ["receipt_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_purchase_return_receipts_warehouse_id"),
        "purchase_return_receipts",
        ["warehouse_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_purchase_return_receipts_workspace_id"),
        "purchase_return_receipts",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "purchase_return_receipt_items",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column(
            "purchase_return_receipt_id", sqlmodel.sql.sqltypes.GUID(), nullable=False
        ),
        sa.Column(
            "purchase_return_item_id", sqlmodel.sql.sqltypes.GUID(), nullable=False
        ),
        sa.Column("product_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column(
            "condition",
            sa.Enum("GOOD", "DAMAGED", "QUARANTINE", name="purchasereturncondition"),
            nullable=False,
        ),
        sa.Column("bin_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "quantity > 0", name="chk_preturn_receipt_item_quantity_positive"
        ),
        sa.ForeignKeyConstraint(
            ["bin_id"],
            ["warehouse_bins.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["purchase_return_item_id"],
            ["purchase_return_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["purchase_return_receipt_id"],
            ["purchase_return_receipts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_purchase_return_receipt_items_purchase_return_item_id"),
        "purchase_return_receipt_items",
        ["purchase_return_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_purchase_return_receipt_items_purchase_return_receipt_id"),
        "purchase_return_receipt_items",
        ["purchase_return_receipt_id"],
        unique=False,
    )
    op.add_column(
        "purchase_return_items",
        sa.Column(
            "received_qty",
            sa.Numeric(precision=12, scale=4),
            nullable=False,
            server_default=sa.text("'0'"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("purchase_return_items", "received_qty")
    op.drop_index(
        op.f("ix_purchase_return_receipt_items_purchase_return_receipt_id"),
        table_name="purchase_return_receipt_items",
    )
    op.drop_index(
        op.f("ix_purchase_return_receipt_items_purchase_return_item_id"),
        table_name="purchase_return_receipt_items",
    )
    op.drop_table("purchase_return_receipt_items")
    op.drop_index(
        op.f("ix_purchase_return_receipts_workspace_id"),
        table_name="purchase_return_receipts",
    )
    op.drop_index(
        op.f("ix_purchase_return_receipts_warehouse_id"),
        table_name="purchase_return_receipts",
    )
    op.drop_index(
        op.f("ix_purchase_return_receipts_receipt_number"),
        table_name="purchase_return_receipts",
    )
    op.drop_index(
        op.f("ix_purchase_return_receipts_purchase_return_id"),
        table_name="purchase_return_receipts",
    )
    op.drop_index(
        op.f("ix_purchase_return_receipts_bin_id"),
        table_name="purchase_return_receipts",
    )
    op.drop_table("purchase_return_receipts")
    op.drop_table("purchase_return_receipt_counters")
    op.execute("DROP TYPE IF EXISTS purchasereturnreceiptstatus CASCADE")
    op.execute("DROP TYPE IF EXISTS purchasereturncondition CASCADE")
    # Note: PostgreSQL does not support DROP VALUE on enum types
    # ### end Alembic commands ###
