"""Add enquiry module

Revision ID: c624e2ac4f47
Revises: d4e9d19b7279
Create Date: 2026-09-03 17:38:45.271332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c624e2ac4f47'
down_revision: Union[str, None] = 'd4e9d19b7279'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enquiry_counters',
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('workspace_id', 'year')
    )
    op.create_table('enquiries',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('enquiry_number', sa.String(length=50), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_whatsapp', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('items_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('whatsapp_message_id', sa.String(length=255), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('assigned_to', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('whatsapp_message_id')
    )
    op.create_index(op.f('ix_enquiries_client_id'), 'enquiries', ['client_id'], unique=False)
    op.create_index(op.f('ix_enquiries_deleted_at'), 'enquiries', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_enquiries_workspace_id'), 'enquiries', ['workspace_id'], unique=False)
    op.create_table('enquiry_items',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('enquiry_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('product_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity_requested', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('uom_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiries.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['uom_id'], ['units_of_measure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enquiry_items_enquiry_id'), 'enquiry_items', ['enquiry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enquiry_items_enquiry_id'), table_name='enquiry_items')
    op.drop_table('enquiry_items')
    op.drop_index(op.f('ix_enquiries_workspace_id'), table_name='enquiries')
    op.drop_index(op.f('ix_enquiries_deleted_at'), table_name='enquiries')
    op.drop_index(op.f('ix_enquiries_client_id'), table_name='enquiries')
    op.drop_table('enquiries')
    op.drop_table('enquiry_counters')
    # ### end Alembic commands ###
