"""add quotations

Revision ID: cb01b6bef962
Revises: c8e1a4f2b6d0
Create Date: 2026-09-01 00:38:07.585778

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cb01b6bef962"
down_revision: Union[str, None] = "c8e1a4f2b6d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quotation_counters",
        sa.Column("workspace_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("last_number", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("workspace_id", "year"),
    )
    op.create_table(
        "quotations",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("workspace_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("client_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column(
            "quotation_number", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("currency", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "SENT",
                "ACCEPTED",
                "REJECTED",
                "EXPIRED",
                "CONVERTED",
                name="quotationstatus",
            ),
            nullable=False,
        ),
        sa.Column("quotation_date", sa.Date(), nullable=False),
        sa.Column("valid_until", sa.Date(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("subtotal >= 0", name="check_quotation_subtotal_positive"),
        sa.CheckConstraint(
            "tax_amount >= 0", name="check_quotation_tax_amount_positive"
        ),
        sa.CheckConstraint("total_amount >= 0", name="check_quotation_total_positive"),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workspace_id", "quotation_number", name="uq_workspace_quotation_number"
        ),
    )
    op.create_index(
        op.f("ix_quotations_client_id"), "quotations", ["client_id"], unique=False
    )
    op.create_index(
        op.f("ix_quotations_created_at"), "quotations", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_quotations_quotation_number"),
        "quotations",
        ["quotation_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_quotations_workspace_id"), "quotations", ["workspace_id"], unique=False
    )
    op.create_table(
        "quotation_events",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("quotation_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "QUOTATION_CREATED",
                "QUOTATION_UPDATED",
                "QUOTATION_SENT",
                "QUOTATION_ACCEPTED",
                "QUOTATION_REJECTED",
                "QUOTATION_EXPIRED",
                "QUOTATION_CONVERTED",
                name="quotationeventtype",
            ),
            nullable=False,
        ),
        sa.Column("previous_status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("new_status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("changed_by", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column(
            "metadata_log", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["changed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["quotation_id"],
            ["quotations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_quotation_events_quotation_id"),
        "quotation_events",
        ["quotation_id"],
        unique=False,
    )
    op.create_table(
        "quotation_items",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("quotation_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("product_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column("uom_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column("sku_snapshot", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("tax_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("discount_percent", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("discount_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("line_net", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("total_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "discount_amount >= 0", name="check_quotation_disc_amt_nonneg"
        ),
        sa.CheckConstraint(
            "discount_percent >= 0", name="check_quotation_disc_pct_nonneg"
        ),
        sa.CheckConstraint("line_net >= 0", name="check_quotation_line_net_nonneg"),
        sa.CheckConstraint("quantity > 0", name="check_quotation_item_qty_positive"),
        sa.CheckConstraint("tax_amount >= 0", name="check_quotation_item_tax_nonneg"),
        sa.CheckConstraint(
            "tax_rate >= 0", name="check_quotation_item_tax_rate_positive"
        ),
        sa.CheckConstraint(
            "total_price >= 0", name="check_quotation_item_total_positive"
        ),
        sa.CheckConstraint(
            "unit_price >= 0", name="check_quotation_item_price_positive"
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["quotation_id"],
            ["quotations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["uom_id"],
            ["units_of_measure.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_quotation_items_product_id"),
        "quotation_items",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_quotation_items_quotation_id"),
        "quotation_items",
        ["quotation_id"],
        unique=False,
    )
    op.add_column(
        "invoices",
        sa.Column("quotation_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
    )
    op.create_index(
        op.f("ix_invoices_quotation_id"), "invoices", ["quotation_id"], unique=True
    )
    op.create_foreign_key(
        "fk_invoices_quotation_id",
        "invoices",
        "quotations",
        ["quotation_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_invoices_quotation_id", "invoices", type_="foreignkey")
    op.drop_index(op.f("ix_invoices_quotation_id"), table_name="invoices")
    op.drop_column("invoices", "quotation_id")
    op.drop_index(op.f("ix_quotation_items_quotation_id"), table_name="quotation_items")
    op.drop_index(op.f("ix_quotation_items_product_id"), table_name="quotation_items")
    op.drop_table("quotation_items")
    op.drop_index(
        op.f("ix_quotation_events_quotation_id"), table_name="quotation_events"
    )
    op.drop_table("quotation_events")
    op.drop_index(op.f("ix_quotations_workspace_id"), table_name="quotations")
    op.drop_index(op.f("ix_quotations_quotation_number"), table_name="quotations")
    op.drop_index(op.f("ix_quotations_created_at"), table_name="quotations")
    op.drop_index(op.f("ix_quotations_client_id"), table_name="quotations")
    op.drop_table("quotations")
    op.drop_table("quotation_counters")
    op.execute("DROP TYPE IF EXISTS quotationeventtype")
    op.execute("DROP TYPE IF EXISTS quotationstatus")
    # ### end Alembic commands ###
