"""baseline

Revision ID: d0be13f0ca49
Revises: 001
Create Date: 2026-05-07 14:14:46.959719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0be13f0ca49'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_idempotency_expires', table_name='idempotency_keys')
    op.drop_index('idx_idempotency_key', table_name='idempotency_keys')
    op.create_index(op.f('ix_idempotency_keys_payment_id'), 'idempotency_keys', ['payment_id'], unique=False)
    op.execute("DO $$ BEGIN CREATE TYPE invoiceeventtype AS ENUM ('INVOICE_CREATED', 'INVOICE_UPDATED', 'INVOICE_SENT', 'INVOICE_VIEWED', 'PAYMENT_ADDED', 'STATUS_CHANGED', 'INVOICE_VOIDED'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    op.execute("ALTER TABLE invoice_events ALTER COLUMN event_type DROP DEFAULT")
    op.execute("ALTER TABLE invoice_events ALTER COLUMN event_type TYPE invoiceeventtype USING event_type::text::invoiceeventtype")
    
    op.create_index(op.f('ix_invoices_created_at'), 'invoices', ['created_at'], unique=False)
    
    op.execute("DO $$ BEGIN CREATE TYPE paymentgateway AS ENUM ('RAZORPAY', 'STRIPE', 'MANUAL'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    op.execute("ALTER TABLE payments ALTER COLUMN gateway TYPE paymentgateway USING gateway::text::paymentgateway")
    
    op.execute("DO $$ BEGIN CREATE TYPE paymentstatus AS ENUM ('PENDING', 'SUCCESS', 'FAILED', 'CANCELLED', 'REFUNDED'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    op.execute("ALTER TABLE payments ALTER COLUMN status TYPE paymentstatus USING status::text::paymentstatus")
    
    op.execute("DO $$ BEGIN CREATE TYPE userrole AS ENUM ('OWNER', 'ADMIN', 'MEMBER'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    op.execute("ALTER TABLE users ALTER COLUMN role TYPE userrole USING role::text::userrole")
    op.drop_index('ix_users_workspace_id', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_workspace_id', 'users', ['workspace_id'], unique=False)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='userrole'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('payments', 'status',
               existing_type=sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'CANCELLED', 'REFUNDED', name='paymentstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('payments', 'gateway',
               existing_type=sa.Enum('RAZORPAY', 'STRIPE', 'MANUAL', name='paymentgateway'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_index(op.f('ix_invoices_created_at'), table_name='invoices')
    op.alter_column('invoice_events', 'event_type',
               existing_type=sa.Enum('INVOICE_CREATED', 'INVOICE_UPDATED', 'INVOICE_SENT', 'INVOICE_VIEWED', 'PAYMENT_ADDED', 'STATUS_CHANGED', 'INVOICE_VOIDED', name='invoiceeventtype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'status_changed'::character varying"))
    op.drop_index(op.f('ix_idempotency_keys_payment_id'), table_name='idempotency_keys')
    op.create_index('idx_idempotency_key', 'idempotency_keys', ['key'], unique=False)
    op.create_index('idx_idempotency_expires', 'idempotency_keys', ['expires_at'], unique=False)
    # ### end Alembic commands ###
