"""Add Wave 7 Inventory Master

Revision ID: d41016da5030
Revises: e217c0bc3af7
Create Date: 2026-08-19 19:44:23.189157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd41016da5030'
down_revision: Union[str, None] = 'e217c0bc3af7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    from sqlalchemy.dialects import postgresql
    transaction_type_enum = postgresql.ENUM('INITIAL', 'RECEIPT', 'ISSUE', 'TRANSFER', 'ADJUSTMENT', name='transactiontype', create_type=False)
    

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouses',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'code', name='uq_workspace_warehouse_code')
    )
    op.create_index(op.f('ix_warehouses_code'), 'warehouses', ['code'], unique=False)
    op.create_index(op.f('ix_warehouses_workspace_id'), 'warehouses', ['workspace_id'], unique=False)
    op.create_table('warehouse_bins',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('warehouse_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('barcode', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'code', name='uq_warehouse_bin_code')
    )
    op.create_index(op.f('ix_warehouse_bins_code'), 'warehouse_bins', ['code'], unique=False)
    op.create_index(op.f('ix_warehouse_bins_warehouse_id'), 'warehouse_bins', ['warehouse_id'], unique=False)
    op.create_table('inventory_levels',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('product_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('warehouse_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('bin_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('on_hand', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reserved', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('damaged', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('damaged >= 0', name='chk_inventory_damaged_positive'),
    sa.CheckConstraint('on_hand >= 0', name='chk_inventory_on_hand_positive'),
    sa.CheckConstraint('reserved >= 0', name='chk_inventory_reserved_positive'),
    sa.ForeignKeyConstraint(['bin_id'], ['warehouse_bins.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'bin_id', name='uq_inventory_product_bin')
    )
    op.create_index(op.f('ix_inventory_levels_bin_id'), 'inventory_levels', ['bin_id'], unique=False)
    op.create_index(op.f('ix_inventory_levels_product_id'), 'inventory_levels', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_levels_warehouse_id'), 'inventory_levels', ['warehouse_id'], unique=False)
    op.create_index(op.f('ix_inventory_levels_workspace_id'), 'inventory_levels', ['workspace_id'], unique=False)
    op.create_table('inventory_transactions',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('workspace_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('product_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('transaction_type', sa.Enum('INITIAL', 'RECEIPT', 'ISSUE', 'TRANSFER', 'ADJUSTMENT', name='transactiontype'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('source_bin_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('destination_bin_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('reference_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reference_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['destination_bin_id'], ['warehouse_bins.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['source_bin_id'], ['warehouse_bins.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_transactions_product_id'), 'inventory_transactions', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_workspace_id'), 'inventory_transactions', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_transactions_workspace_id'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_product_id'), table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    op.drop_index(op.f('ix_inventory_levels_workspace_id'), table_name='inventory_levels')
    op.drop_index(op.f('ix_inventory_levels_warehouse_id'), table_name='inventory_levels')
    op.drop_index(op.f('ix_inventory_levels_product_id'), table_name='inventory_levels')
    op.drop_index(op.f('ix_inventory_levels_bin_id'), table_name='inventory_levels')
    op.drop_table('inventory_levels')
    op.drop_index(op.f('ix_warehouse_bins_warehouse_id'), table_name='warehouse_bins')
    op.drop_index(op.f('ix_warehouse_bins_code'), table_name='warehouse_bins')
    op.drop_table('warehouse_bins')
    op.drop_index(op.f('ix_warehouses_workspace_id'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_code'), table_name='warehouses')
    op.drop_table('warehouses')
    # ### end Alembic commands ###
