"""add_debit_note_issued_event

Revision ID: d4e9d19b7279
Revises: efe95b8ac5ec
Create Date: 2026-09-03 06:35:52.899454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4e9d19b7279'
down_revision: Union[str, None] = 'efe95b8ac5ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE invoiceeventtype ADD VALUE 'DEBIT_NOTE_ISSUED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: PostgreSQL does not support dropping ENUM values easily.
    pass
