"""Add Wave 5 Payment Methods and PDC

Revision ID: e217c0bc3af7
Revises: 784076ef11b9
Create Date: 2026-08-19 19:14:41.068488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e217c0bc3af7'
down_revision: Union[str, None] = '784076ef11b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    from sqlalchemy.dialects import postgresql
    payment_method_enum = postgresql.ENUM('CASH', 'BANK_TRANSFER', 'CHEQUE', 'PDC', 'CREDIT_CARD', name='paymentmethod', create_type=False)
    payment_method_enum.create(op.get_bind(), checkfirst=True)
    
    pdc_status_enum = postgresql.ENUM('RECEIVED', 'DEPOSITED', 'CLEARED', 'BOUNCED', 'RETURNED', name='pdcstatus', create_type=False)
    pdc_status_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('payment_method', sa.Enum('CASH', 'BANK_TRANSFER', 'CHEQUE', 'PDC', 'CREDIT_CARD', name='paymentmethod'), nullable=False))
    op.add_column('payments', sa.Column('reference_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('payments', sa.Column('bank_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('payments', sa.Column('pdc_date', sa.Date(), nullable=True))
    op.add_column('payments', sa.Column('pdc_status', sa.Enum('RECEIVED', 'DEPOSITED', 'CLEARED', 'BOUNCED', 'RETURNED', name='pdcstatus'), nullable=True))
    op.drop_column('payments', 'gateway')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('gateway', postgresql.ENUM('RAZORPAY', 'STRIPE', 'MANUAL', name='paymentgateway'), autoincrement=False, nullable=True))
    op.drop_column('payments', 'pdc_status')
    op.drop_column('payments', 'pdc_date')
    op.drop_column('payments', 'bank_name')
    op.drop_column('payments', 'reference_number')
    op.drop_column('payments', 'payment_method')
    # ### end Alembic commands ###
