"""Add tax debit notes

Revision ID: efe95b8ac5ec
Revises: 1a30af047312
Create Date: 2026-09-02 19:40:06.667859

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "efe95b8ac5ec"
down_revision: Union[str, None] = "1a30af047312"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tax_debit_note_counters",
        sa.Column("workspace_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("last_sequence", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("workspace_id", "year"),
    )
    op.create_table(
        "tax_debit_notes",
        sa.Column("debit_note_number", sa.String(length=50), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("currency", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("issue_date", sa.Date(), nullable=False),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reason_notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("subtotal", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "original_invoice_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("original_issue_date", sa.Date(), nullable=True),
        sa.Column("invoice_kind", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("seller_name_snapshot", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("seller_trn_snapshot", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("seller_address_snapshot", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("buyer_name_snapshot", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("buyer_trn_snapshot", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("buyer_address_snapshot", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("workspace_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("client_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("invoice_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tax_debit_notes_client_id"),
        "tax_debit_notes",
        ["client_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tax_debit_notes_deleted_at"),
        "tax_debit_notes",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tax_debit_notes_invoice_id"),
        "tax_debit_notes",
        ["invoice_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tax_debit_notes_workspace_id"),
        "tax_debit_notes",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "tax_debit_note_items",
        sa.Column("product_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column("internal_sku", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("tax_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("discount_percent", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("total_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("tax_debit_note_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("invoice_item_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["invoice_item_id"],
            ["invoice_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tax_debit_note_id"],
            ["tax_debit_notes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tax_debit_note_items_tax_debit_note_id"),
        "tax_debit_note_items",
        ["tax_debit_note_id"],
        unique=False,
    )
    op.add_column(
        "invoices",
        sa.Column(
            "amount_debited",
            sa.Numeric(precision=12, scale=2),
            server_default="0",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invoices", "amount_debited")
    op.drop_index(
        op.f("ix_tax_debit_note_items_tax_debit_note_id"),
        table_name="tax_debit_note_items",
    )
    op.drop_table("tax_debit_note_items")
    op.drop_index(op.f("ix_tax_debit_notes_workspace_id"), table_name="tax_debit_notes")
    op.drop_index(op.f("ix_tax_debit_notes_invoice_id"), table_name="tax_debit_notes")
    op.drop_index(op.f("ix_tax_debit_notes_deleted_at"), table_name="tax_debit_notes")
    op.drop_index(op.f("ix_tax_debit_notes_client_id"), table_name="tax_debit_notes")
    op.drop_table("tax_debit_notes")
    op.drop_table("tax_debit_note_counters")
    # ### end Alembic commands ###
