#!/usr/bin/env python3
"""
Graphify regeneration helper for the RezorPay repo.

Builds the layered Graphify documentation system in graphify-out/:

  graph.html                  high-level aggregated community overview
                              (deterministic hub labels; no LLM required)
  GRAPH_TREE.html             project/file hierarchy (D3 collapsible tree)
  rezorpay_pro-callflow.html  architecture / call-flow sections (Mermaid)
  full-detail.html            the complete detailed graph
  subgraphs/<name>.html       focused subsystem graphs
  GRAPH_REPORT.md             Graphify's own text report
  graph.json                  canonical machine-readable graph

Every artifact is generated by Graphify itself (CLI subprocess for
tree/callflow/labels, `graphify.export.to_html` for graphs that need a custom
output path). No application code is touched.

Usage:
  python scripts/graphify/regenerate.py [--repo PATH] [--force-extract]
                                        [--dry-run]

  --force-extract  re-extract code (graphify update) even if the graph appears
                   current (built_at_commit == HEAD). Default is to re-cluster
                   the existing graph when it is already up to date.
  --dry-run        print the subsystem/node sizes that would be generated
                   without writing any files.

Graphify must be installed. It is resolved, in order, from:
  1. $GRAPHIFY_VENV        (directory containing Scripts/graphify.exe on
                            Windows or bin/graphify on POSIX)
  2. `graphify` on PATH
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

OUT_NAME = "graphify-out"
SUBSYSTEM_DIR = "subgraphs"

# Subsystem focal-file sets. These are exact repository paths (forward slash),
# taken from the actual files Graphify indexed in graph.json. Only files that
# really exist in the codebase appear here, so a subsystem is never invented.
SUBSYSTEMS: dict[str, tuple[str, list[str]]] = {
    "inventory": (
        "Inventory: stock transfers, reservations, counts, adjustments, landed cost",
        [
            "backend/app/routers/inventory.py",
            "backend/app/schemas/inventory.py",
            "backend/app/models/inventory.py",
            "backend/app/services/inventory_ledger.py",
            "backend/app/services/stock_transfer_service.py",
            "backend/app/services/stock_reservation_service.py",
            "backend/app/services/stock_count_service.py",
            "backend/app/services/transfer_number.py",
            "backend/app/services/stock_count_number.py",
            "backend/app/models/stock_transfer.py",
            "backend/app/models/stock_reservation.py",
            "backend/app/models/stock_count.py",
            "backend/app/models/landed_cost.py",
            "backend/app/schemas/stock_transfer.py",
            "backend/app/schemas/stock_reservation.py",
            "backend/app/schemas/stock_count.py",
            "backend/alembic/versions/c6b3e7a9d2f0_add_stock_transfers.py",
            "backend/alembic/versions/e1f5b8a2c3d4_add_stock_counts.py",
            "backend/alembic/versions/b2a4d6f8e1c0_add_stock_reservations.py",
            "backend/alembic/versions/d41016da5030_add_wave_7_inventory_master.py",
            "backend/alembic/versions/985774b20cc8_add_d22_landed_cost_allocations.py",
            "frontend/src/api/inventory.ts",
            "frontend/src/pages/Inventory.tsx",
            "backend/tests/test_stock_transfers.py",
            "backend/tests/test_stock_reservations.py",
            "backend/tests/test_stock_counts.py",
            "backend/tests/test_landed_cost.py",
        ],
    ),
    "procurement-requests": (
        "Procurement requests (PPR), enquiries and RFQ awards",
        [
            "backend/app/routers/procurement.py",
            "backend/app/routers/enquiries.py",
            "backend/app/routers/rfq.py",
            "backend/app/schemas/procurement.py",
            "backend/app/schemas/enquiry.py",
            "backend/app/schemas/rfq.py",
            "backend/app/models/procurement.py",
            "backend/app/models/enquiry.py",
            "backend/app/models/enquiry_item.py",
            "backend/app/models/rfq.py",
            "backend/app/models/rfq_counter.py",
            "backend/app/models/rfq_award_counter.py",
            "backend/app/models/pr_counter.py",
            "backend/app/services/enquiry_service.py",
            "backend/app/services/award_service.py",
            "backend/app/services/rfq_number.py",
            "backend/app/services/pr_number.py",
            "backend/app/services/award_number.py",
            "backend/alembic/versions/0abb440e0fc9_add_wave_8_procurement_requests.py",
            "backend/alembic/versions/64d6ac9e5b49_add_wave_9_rfq_master.py",
            "backend/alembic/versions/6d27f753e9e3_rfq_award_flow_counters_threshold_.py",
            "frontend/src/api/procurement.ts",
            "frontend/src/api/enquiries.ts",
            "frontend/src/api/rfq.ts",
            "frontend/src/pages/Procurement.tsx",
            "frontend/src/pages/enquiries/Enquiries.tsx",
            "frontend/src/pages/enquiries/EnquiryDetail.tsx",
            "frontend/src/pages/RFQ.tsx",
            "backend/tests/test_enquiries.py",
            "backend/tests/test_rfq_awards.py",
        ],
    ),
    "supplier-purchase-orders": (
        "Supplier purchase orders (SPO), amendments and GRN",
        [
            "backend/app/routers/spo.py",
            "backend/app/routers/grn.py",
            "backend/app/schemas/spo.py",
            "backend/app/schemas/grn.py",
            "backend/app/models/spo.py",
            "backend/app/models/grn.py",
            "backend/app/models/spo_counter.py",
            "backend/app/models/grn_counter.py",
            "backend/app/services/spo_service.py",
            "backend/app/services/grn_service.py",
            "backend/app/services/spo_number.py",
            "backend/app/services/grn_number.py",
            "backend/alembic/versions/345906985988_add_wave_10_supplier_purchase_orders.py",
            "backend/alembic/versions/2a98d90a2f79_add_wave_11_grn.py",
            "backend/alembic/versions/63f069419100_add_spo_architecture.py",
            "backend/alembic/versions/5f24e4eb1428_add_grn_models.py",
            "backend/alembic/versions/b7e2f4a9c1d3_add_spo_counters.py",
            "backend/alembic/versions/9f3a2c1e5d84_add_gapless_pr_rfq_grn_counters.py",
            "frontend/src/api/spo.ts",
            "frontend/src/api/grn.ts",
            "frontend/src/pages/SPO.tsx",
            "frontend/src/pages/SPOBuilder.tsx",
            "frontend/src/pages/SPODetail.tsx",
            "frontend/src/pages/GRN.tsx",
            "frontend/src/pages/GRNDetail.tsx",
            "backend/tests/test_spo.py",
            "backend/tests/test_spo_amendments.py",
            "backend/tests/test_grn.py",
            "backend/tests/test_e2e_spo.py",
            "backend/tests/test_e2e_grn.py",
        ],
    ),
    "purchase-returns": (
        "Purchase returns and supplier debit notes",
        [
            "backend/app/routers/purchase_returns.py",
            "backend/app/routers/supplier_debit_notes.py",
            "backend/app/schemas/purchase_returns.py",
            "backend/app/schemas/supplier_debit_notes.py",
            "backend/app/models/purchase_return.py",
            "backend/app/models/supplier_debit_note.py",
            "backend/app/services/purchase_return_service.py",
            "backend/app/services/supplier_debit_note_service.py",
            "backend/app/services/purchase_return_number.py",
            "backend/app/services/supplier_debit_note_number.py",
            "backend/alembic/versions/b4a2c6e8f10d_add_purchase_returns_and_supplier_debit_notes.py",
            "backend/tests/test_purchase_returns.py",
            "backend/tests/test_supplier_debit_notes.py",
        ],
    ),
    "supplier-invoices": (
        "Supplier invoices, events and VAT compliance",
        [
            "backend/app/routers/supplier_invoices.py",
            "backend/app/schemas/supplier_invoices.py",
            "backend/app/models/supplier_invoice.py",
            "backend/app/services/supplier_invoice_service.py",
            "backend/app/services/supplier_invoice_events.py",
            "backend/app/models/supplier_invoice_event.py",
            "backend/app/services/vat_compliance_service.py",
            "backend/app/schemas/vat_compliance.py",
            "backend/alembic/versions/633b2df1fb55_add_supplier_invoice_models.py",
            "backend/alembic/versions/9788f2686209_supplier_invoice_events.py",
            "backend/alembic/versions/12bdad2ae924_fix_supplier_invoice_decimal_types.py",
            "backend/alembic/versions/9ab488fc07a8_fix_supplier_id_fk.py",
            "frontend/src/api/supplier-invoices.ts",
            "frontend/src/pages/SupplierInvoices.tsx",
            "frontend/src/pages/SupplierInvoiceDetail.tsx",
            "backend/tests/test_supplier_invoice_events.py",
            "backend/tests/test_vat_compliance.py",
            "backend/tests/test_e2e_3way_match.py",
        ],
    ),
    "supplier-payments": (
        "Supplier payments, PDC, reversals and supplier statements",
        [
            "backend/app/routers/supplier_payments.py",
            "backend/app/schemas/supplier_payments.py",
            "backend/app/schemas/supplier_statements.py",
            "backend/app/schemas/suppliers.py",
            "backend/app/models/supplier_payment.py",
            "backend/app/models/supplier.py",
            "backend/app/services/supplier_payment_service.py",
            "backend/app/services/supplier_payment_reversal_service.py",
            "backend/app/services/supplier_statement_service.py",
            "backend/app/services/supplier_pdc_service.py",
            "backend/app/services/pdc_service.py",
            "backend/app/services/supplier_product_service.py",
            "backend/app/routers/suppliers.py",
            "backend/app/schemas/ap_aging.py",
            "backend/alembic/versions/a3f4c7d9e1b2_add_supplier_payments.py",
            "backend/alembic/versions/234d5639ef8c_add_supplier_pdc_columns.py",
            "backend/alembic/versions/e217c0bc3af7_add_wave_5_payment_methods_and_pdc.py",
            "backend/alembic/versions/784076ef11b9_add_wave_4_supplier_master.py",
            "frontend/src/api/suppliers.ts",
            "frontend/src/api/supplier-invoices.ts",
            "backend/tests/test_supplier_payments.py",
            "backend/tests/test_supplier_payment_reversal.py",
            "backend/tests/test_supplier_statement.py",
            "backend/tests/test_supplier_statement_dn.py",
            "backend/tests/test_supplier_pdc.py",
            "backend/tests/test_ap_aging.py",
            "backend/tests/test_supplier_products.py",
        ],
    ),
    "sales-customers-quotations-lpos": (
        "Customers, quotations, customer LPOs and product catalog / pricing",
        [
            "backend/app/routers/clients.py",
            "backend/app/schemas/clients.py",
            "backend/app/models/client.py",
            "backend/app/routers/quotations.py",
            "backend/app/schemas/quotations.py",
            "backend/app/models/quotation.py",
            "backend/app/models/quotation_item.py",
            "backend/app/models/quotation_event.py",
            "backend/app/models/quotation_counter.py",
            "backend/app/services/quotation_service.py",
            "backend/app/services/quotation_support.py",
            "backend/app/services/quotation_number.py",
            "backend/app/routers/customer_purchase_orders.py",
            "backend/app/schemas/customer_purchase_orders.py",
            "backend/app/models/customer_purchase_order.py",
            "backend/app/models/customer_purchase_order_item.py",
            "backend/app/models/customer_purchase_order_event.py",
            "backend/app/models/lpo_counter.py",
            "backend/app/services/customer_po_service.py",
            "backend/app/services/customer_po_support.py",
            "backend/app/services/lpo_number.py",
            "backend/app/routers/products.py",
            "backend/app/schemas/products.py",
            "backend/app/models/product.py",
            "backend/app/services/product_service.py",
            "backend/app/services/pricing_service.py",
            "backend/alembic/versions/cb01b6bef962_add_quotations.py",
            "backend/alembic/versions/59084165d346_add_customer_lpos.py",
            "backend/alembic/versions/d3e4c7fdb29f_add_wave_3_product_master.py",
            "backend/alembic/versions/1a30af047312_add_product_electrical_specs.py",
            "backend/alembic/versions/4ec511b03a6f_make_client_email_nullable.py",
            "frontend/src/api/clients.ts",
            "frontend/src/api/quotations.ts",
            "frontend/src/api/lpos.ts",
            "frontend/src/api/products.ts",
            "frontend/src/pages/Clients.tsx",
            "frontend/src/pages/clientHelpers.tsx",
            "frontend/src/pages/Quotations.tsx",
            "frontend/src/pages/QuotationForm.tsx",
            "frontend/src/pages/QuotationDetail.tsx",
            "frontend/src/pages/QuotationStatusBadge.tsx",
            "frontend/src/pages/quotationHelpers.tsx",
            "frontend/src/pages/Lpos.tsx",
            "frontend/src/pages/LpoForm.tsx",
            "frontend/src/pages/LpoDetail.tsx",
            "frontend/src/pages/lpoHelpers.tsx",
            "frontend/src/pages/LpoStatusBadge.tsx",
            "frontend/src/pages/Products.tsx",
            "frontend/src/pages/productUi.tsx",
            "frontend/src/pages/ProductDetailPanel.tsx",
            "frontend/src/pages/ProductCatalogTabs.tsx",
            "frontend/src/pages/catalogLinePricing.tsx",
            "frontend/src/components/pdf/LpoPDF.tsx",
            "frontend/src/components/pdf/LpoPdfPreview.tsx",
            "frontend/src/components/pdf/QuotationPDF.tsx",
            "frontend/src/components/pdf/QuotationPdfPreview.tsx",
            "backend/tests/test_customer_lpos.py",
            "backend/tests/test_quotations.py",
            "backend/tests/test_products.py",
            "backend/tests/test_pricing.py",
            "backend/tests/test_product_electrical_specs.py",
        ],
    ),
    "accounts-receivable": (
        "Sales invoices, payments received, credit control, credit notes, delivery and tax debit notes",
        [
            "backend/app/routers/invoices.py",
            "backend/app/schemas/invoices.py",
            "backend/app/models/invoice.py",
            "backend/app/models/invoice_item.py",
            "backend/app/models/invoice_counter.py",
            "backend/app/models/invoice_event.py",
            "backend/app/services/invoice_service.py",
            "backend/app/services/invoice_number.py",
            "backend/app/routers/credit_notes.py",
            "backend/app/schemas/credit_notes.py",
            "backend/app/models/credit_note.py",
            "backend/app/models/credit_note_item.py",
            "backend/app/models/credit_note_counter.py",
            "backend/app/models/credit_note_event.py",
            "backend/app/services/credit_note_service.py",
            "backend/app/services/credit_note_support.py",
            "backend/app/services/credit_note_number.py",
            "backend/app/routers/delivery_notes.py",
            "backend/app/schemas/delivery_notes.py",
            "backend/app/models/delivery_note.py",
            "backend/app/models/delivery_note_item.py",
            "backend/app/models/delivery_note_event.py",
            "backend/app/models/dn_counter.py",
            "backend/app/services/delivery_note_service.py",
            "backend/app/services/delivery_note_support.py",
            "backend/app/services/dn_number.py",
            "backend/app/routers/debit_notes.py",
            "backend/app/schemas/tax_debit_notes.py",
            "backend/app/models/tax_debit_note.py",
            "backend/app/services/tax_debit_note_service.py",
            "backend/app/services/tax_debit_note_support.py",
            "backend/app/services/tax_debit_note_number.py",
            "backend/app/routers/payments.py",
            "backend/app/schemas/payments.py",
            "backend/app/models/payment.py",
            "backend/app/services/payment_service.py",
            "backend/app/services/credit_control_service.py",
            "backend/app/models/credit_status_event.py",
            "backend/alembic/versions/a7c4e9d2b105_add_delivery_notes.py",
            "backend/alembic/versions/b8d5f0c3a216_add_credit_notes.py",
            "backend/alembic/versions/d4e9d19b7279_add_debit_note_issued_event.py",
            "backend/alembic/versions/c8e1a4f2b6d0_fta_tax_invoice_fields.py",
            "backend/alembic/versions/e1f0aabb01aa_add_check_amount_debited_nonneg.py",
            "backend/alembic/versions/a1b2c3d4e5f6_align_tax_debit_note_items.py",
            "backend/alembic/versions/9f3a7c2e1d04_add_client_credit_control.py",
            "frontend/src/api/invoices.ts",
            "frontend/src/api/creditNotes.ts",
            "frontend/src/api/deliveryNotes.ts",
            "frontend/src/api/debitNotes.ts",
            "frontend/src/pages/Invoices.tsx",
            "frontend/src/pages/InvoicePayments.tsx",
            "frontend/src/pages/InvoiceArPanel.tsx",
            "frontend/src/pages/CreditNotes.tsx",
            "frontend/src/pages/CreditNoteForm.tsx",
            "frontend/src/pages/CreditNoteDetail.tsx",
            "frontend/src/pages/CreditNoteStatusBadge.tsx",
            "frontend/src/pages/creditNoteHelpers.tsx",
            "frontend/src/pages/DeliveryNotes.tsx",
            "frontend/src/pages/DeliveryNoteForm.tsx",
            "frontend/src/pages/DeliveryNoteDetail.tsx",
            "frontend/src/pages/DeliveryNoteStatusBadge.tsx",
            "frontend/src/pages/DebitNotes.tsx",
            "frontend/src/pages/DebitNoteForm.tsx",
            "frontend/src/pages/DebitNoteDetail.tsx",
            "frontend/src/pages/DebitNoteStatusBadge.tsx",
            "frontend/src/pages/debitNoteHelpers.tsx",
            "frontend/src/pages/paymentHelpers.tsx",
            "frontend/src/components/pdf/InvoicePDF.tsx",
            "frontend/src/components/pdf/InvoicePdfPreview.tsx",
            "frontend/src/components/pdf/CreditNotePDF.tsx",
            "frontend/src/components/pdf/CreditNotePdfPreview.tsx",
            "frontend/src/components/pdf/DeliveryNotePDF.tsx",
            "frontend/src/components/pdf/DeliveryNotePdfPreview.tsx",
            "frontend/src/components/pdf/TaxDebitNotePDF.tsx",
            "frontend/src/components/pdf/TaxDebitNotePdfPreview.tsx",
            "backend/tests/test_invoices.py",
            "backend/tests/test_credit_notes.py",
            "backend/tests/test_delivery_notes.py",
            "backend/tests/test_credit_control.py",
            "backend/tests/test_tax_debit_notes.py",
            "backend/tests/test_concurrent_numbering.py",
        ],
    ),
    "reports-analytics": (
        "Reports, analytics dashboard, AR/AP aging and statement export",
        [
            "backend/app/routers/analytics.py",
            "backend/app/schemas/analytics.py",
            "backend/app/services/analytics_service.py",
            "backend/app/routers/reports.py",
            "backend/app/routers/dashboard.py",
            "backend/app/schemas/dashboard.py",
            "backend/app/routers/ar_aging.py",
            "backend/app/schemas/ar_aging.py",
            "backend/app/schemas/ap_aging.py",
            "backend/app/services/ar_aging.py",
            "backend/app/services/ar_statement_service.py",
            "backend/app/services/statement_export_service.py",
            "backend/app/schemas/ar_statements.py",
            "frontend/src/api/analytics.ts",
            "frontend/src/api/reports.ts",
            "frontend/src/api/dashboard.ts",
            "frontend/src/pages/Reports.tsx",
            "frontend/src/pages/Dashboard.tsx",
            "frontend/src/pages/ArStatement.tsx",
            "frontend/src/pages/statementHelpers.tsx",
            "frontend/src/components/pdf/StatementPDF.tsx",
            "frontend/src/components/pdf/StatementPdfPreview.tsx",
            "backend/tests/test_analytics.py",
            "backend/tests/test_ar_aging.py",
            "backend/tests/test_ap_aging.py",
            "backend/tests/test_ar_statement.py",
            "backend/tests/test_ar_statement_tdn.py",
            "backend/tests/test_statement_export.py",
        ],
    ),
    "auth-rbac": (
        "Authentication, JWT, RBAC, workspaces and multi-tenant isolation",
        [
            "backend/app/auth/router.py",
            "backend/app/auth/utils.py",
            "backend/app/auth/dependencies.py",
            "backend/app/auth/__init__.py",
            "backend/app/routers/workspaces.py",
            "backend/app/schemas/workspaces.py",
            "backend/app/models/workspace.py",
            "backend/app/models/user.py",
            "backend/app/main.py",
            "backend/app/limiter.py",
            "frontend/src/pages/Login.tsx",
            "frontend/src/pages/Register.tsx",
            "frontend/src/pages/Settings.tsx",
            "frontend/src/contexts/AuthContext.tsx",
            "frontend/src/components/AuthGuard.tsx",
            "frontend/src/components/Layout.tsx",
            "frontend/src/types/auth.ts",
            "frontend/src/api/workspaces.ts",
            "frontend/src/api/client.ts",
            "backend/tests/test_auth.py",
            "backend/tests/test_multi_tenant_isolation.py",
            "frontend/e2e/member-gating.spec.ts",
        ],
    ),
    "communications": (
        "WhatsApp and email communications",
        [
            "backend/app/routers/comms_whatsapp.py",
            "backend/app/routers/comms_emails.py",
            "backend/app/services/whatsapp_service.py",
            "backend/app/services/email_service.py",
            "backend/app/models/whatsapp_message.py",
            "backend/app/models/email_log.py",
            "backend/app/schemas/whatsapp_comms.py",
            "backend/app/schemas/email_comms.py",
            "backend/app/services/pdf_service.py",
            "backend/alembic/versions/c5b7a3e9f21d_add_whatsapp_messages.py",
            "backend/alembic/versions/3d3f24d6ee00_add_email_log.py",
            "backend/tests/test_whatsapp_comms.py",
            "backend/tests/test_email_comms.py",
        ],
    ),
}

# Neighbours brought into a subsystem graph are restricted to real repository
# source files, so generated config (`package.json`, `tsconfig.json`,
# `.oxlintrc.json`) and stray root scripts never leak into a slice.
NEIGHBOR_ALLOWLIST = (
    "backend/app/",
    "backend/tests/",
    "backend/alembic/",
    "frontend/src/",
    "frontend/e2e/",
    ".claude/commands/",
)

MAX_NODES = 1300


def _norm(p: str) -> str:
    return str(Path(p)).replace("\\", "/").lower()


def find_graphify() -> str:
    """Return the path/argv prefix used to invoke the graphify CLI."""
    venv = os.environ.get("GRAPHIFY_VENV")
    if venv:
        exe = Path(venv) / ("Scripts/graphify.exe" if os.name == "nt" else "bin/graphify")
        if exe.exists():
            return str(exe)
        print(f"[graphify] GRAPHIFY_VENV set but {exe} not found", file=sys.stderr)
    cli = shutil.which("graphify")
    if cli:
        return cli
    probe = subprocess.run([sys.executable, "-m", "graphify", "--version"],
                           capture_output=True)
    if probe.returncode == 0:
        return [sys.executable, "-m", "graphify"]
    print(
        "error: graphify not found. Install it (pip install graphifyy) or set "
        "GRAPHIFY_VENV to the venv directory.",
        file=sys.stderr,
    )
    sys.exit(1)


def run_cli(graphify: str | list[str], *args: str) -> None:
    cmd = [*graphify, *args] if isinstance(graphify, list) else [graphify, *args]
    print(f"[graphify] {' '.join(str(a) for a in cmd)}")
    proc = subprocess.run(cmd)
    if proc.returncode != 0:
        print(f"error: command failed ({proc.returncode})", file=sys.stderr)
        sys.exit(proc.returncode)


def git_head(repo: Path) -> str:
    try:
        return subprocess.run(
            ["git", "rev-parse", "HEAD"], cwd=repo, capture_output=True, text=True
        ).stdout.strip()
    except Exception:
        return ""


def load_knowledge(out_dir: Path):
    raw = json.loads((out_dir / "graph.json").read_text(encoding="utf-8"))
    nodes = [dict(n) for n in raw.get("nodes", [])]
    links = [dict(l) for l in raw.get("links", raw.get("edges", []))]
    return raw, nodes, links


def build_adj(nodes: list[dict], links: list[dict]) -> dict[str, set[str]]:
    adj: dict[str, set[str]] = {n["id"]: set() for n in nodes}
    for l in links:
        a, b = l.get("source"), l.get("target")
        if a in adj and b in adj:
            adj[a].add(b)
            adj[b].add(a)
    return adj


def slice_ids(nodes: list[dict], adj: dict[str, set[str]],
              files: list[str], allowlist: tuple[str, ...]) -> set[str]:
    file_by_id = {n["id"]: n for n in nodes}
    focal = {n["id"] for n in nodes if _norm(n.get("source_file", "") or "") in files}
    selected = set(focal)
    for fid in focal:
        for nb in adj.get(fid, ()):
            nf = _norm(file_by_id[nb].get("source_file", "") or "")
            if any(nf.startswith(p) for p in allowlist):
                selected.add(nb)
    if len(selected) > MAX_NODES:
        selected = set(focal)
        for fid in focal:
            for nb in adj.get(fid, ()):
                nf = _norm(file_by_id[nb].get("source_file", "") or "")
                if nf.startswith("backend/app/") or nf.startswith("backend/alembic/"):
                    selected.add(nb)
    if len(selected) > MAX_NODES + 500:
        selected = set(focal)
        for fid in focal:
            for nb in adj.get(fid, ()):
                nf = _norm(file_by_id[nb].get("source_file", "") or "")
                if nf.startswith("backend/app/"):
                    selected.add(nb)
    return selected


def emit_html(py: str, out_dir: Path, out_path: Path, selected_ids: set[str] | None) -> tuple[int, int]:
    """Render an interactive HTML via Graphify's own to_html (custom output path)."""
    ids_json = json.dumps(sorted(selected_ids)) if selected_ids is not None else "None"
    script = f"""
import json, sys
from pathlib import Path
from networkx.readwrite import json_graph as _jg
from graphify.export import to_html as _to_html

out_dir = Path({str(out_dir)!r})
out = Path({str(out_path)!r})
raw = json.loads((out_dir / "graph.json").read_text(encoding="utf-8"))
ids = {ids_json}
if ids is not None:
    keep = set(ids)
    raw["nodes"] = [n for n in raw["nodes"] if n["id"] in keep]
    raw["links"] = [e for e in raw.get("links", raw.get("edges", []))
                    if e.get("source") in keep and e.get("target") in keep]
    raw["directed"] = False
G = _jg.node_link_graph(raw, edges="links")
communities = {{}}
for nid, data in G.nodes(data=True):
    cid = data.get("community")
    if cid is None:
        continue
    try:
        cid = int(cid)
    except (TypeError, ValueError):
        continue
    communities.setdefault(cid, []).append(str(nid))
labels = {{}}
lbl = out_dir / ".graphify_labels.json"
if lbl.exists():
    labels = {{int(k): v for k, v in json.loads(lbl.read_text(encoding="utf-8")).items()}}
labels = {{cid: name for cid, name in labels.items() if cid in communities}}
ok = _to_html(G, communities, str(out), community_labels=labels or None, node_limit=6000)
print(f"NODES={{G.number_of_nodes()}} EDGES={{G.number_of_edges()}}")
if not ok:
    print("to_html returned False", file=sys.stderr)
    sys.exit(2)
"""
    import tempfile
    fd, tmp = tempfile.mkstemp(suffix=".py", prefix="graphify_gen_")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(script)
        proc = subprocess.run([py, tmp], capture_output=True, text=True)
    finally:
        try:
            os.unlink(tmp)
        except OSError:
            pass
    if proc.returncode != 0:
        print(proc.stdout, file=sys.stderr)
        print(proc.stderr, file=sys.stderr)
        print(f"error: to_html failed for {out_path}", file=sys.stderr)
        sys.exit(proc.returncode)
    for line in (proc.stdout or "").splitlines():
        if line.startswith("NODES="):
            match = re.match(r"NODES=(\d+)\s+EDGES=(\d+)", line)
            if match:
                return int(match.group(1)), int(match.group(2))
    return -1, -1


def main() -> None:
    ap = argparse.ArgumentParser(description="Regenerate the RezorPay Graphify layer")
    ap.add_argument("--repo", default=None, help="repository root (default: two levels above this script)")
    ap.add_argument("--force-extract", action="store_true", help="re-extract code even if the graph looks current")
    ap.add_argument("--dry-run", action="store_true", help="print sizes only, write nothing")
    args = ap.parse_args()

    repo = Path(args.repo).resolve() if args.repo else Path(__file__).resolve().parents[2]
    out_dir = repo / OUT_NAME
    sub_dir = out_dir / SUBSYSTEM_DIR

    if args.dry_run:
        try:
            _, nodes, links = load_knowledge(out_dir)
        except FileNotFoundError:
            print(f"error: {out_dir / 'graph.json'} not found", file=sys.stderr)
            sys.exit(1)
        adj = build_adj(nodes, links)
        print(f"graph: {len(nodes)} nodes / {len(links)} edges")
        for name, (title, files) in SUBSYSTEMS.items():
            sel = slice_ids(nodes, adj, files, NEIGHBOR_ALLOWLIST)
            file_by_id = {n["id"]: n for n in nodes}
            focal = {n["id"] for n in nodes if _norm(n.get("source_file", "") or "") in files}
            if not focal:
                print(f"  {name}: no focal nodes - SKIP")
                continue
            e = sum(1 for l in links if l.get("source") in sel and l.get("target") in sel)
            print(f"  {name}: focal={len(focal)} total={len(sel)} edges={e}")
        return

    graphify = find_graphify()
    if isinstance(graphify, list):
        graphify_cli: list[str] = graphify
        py = graphify_cli[0]
    else:
        graphify_cli = [graphify]
        python = shutil.which("python") or sys.executable
        py = (graphify[:-len("graphify.exe")] + "python.exe"
              if graphify.endswith("graphify.exe") else python)

    head = git_head(repo)
    graph_json = out_dir / "graph.json"
    run_extract = args.force_extract
    if graph_json.exists():
        try:
            built = json.loads(graph_json.read_text(encoding="utf-8")).get("built_at_commit")
        except Exception:
            built = None
        if built == head:
            print(f"[graphify] graph.json up to date at {head}")
        else:
            run_extract = True
            print(f"[graphify] graph is stale (built {built} != HEAD {head})")
    else:
        run_extract = True

    if run_extract:
        run_cli(graphify_cli, "update", str(repo))
    else:
        print("[graphify] skipping extract (graph already at HEAD)")

    # STEP 3: high-level overview with deterministic hub labels (never --no-label).
    run_cli(graphify_cli, "cluster-only", str(repo))

    # STEP 4: hierarchy.
    run_cli(graphify_cli, "tree", "--graph", str(graph_json),
            "--output", str(out_dir / "GRAPH_TREE.html"))

    # STEP 5: call flow.
    run_cli(graphify_cli, "export", "callflow-html", str(repo),
            "--output", str(out_dir / "rezorpay_pro-callflow.html"))

    # STEPS 6-7: subsystem graphs + STEP 8: full detail (custom output paths).
    _, nodes, links = load_knowledge(out_dir)
    adj = build_adj(nodes, links)
    sub_dir.mkdir(parents=True, exist_ok=True)
    results: list[tuple[str, int, int]] = []

    for name, (title, files) in SUBSYSTEMS.items():
        sel = slice_ids(nodes, adj, files, NEIGHBOR_ALLOWLIST)
        if not sel:
            print(f"[graphify] subgraph '{name}': no focal nodes - SKIPPED")
            continue
        out = sub_dir / f"{name}.html"
        n, e = emit_html(py, out_dir, out, sel)
        results.append((f"subgraphs/{name}.html", n, e))

    full_out = out_dir / "full-detail.html"
    n, e = emit_html(py, out_dir, full_out, None)
    results.append(("full-detail.html", n, e))

    print("\n=== Graphify regeneration complete ===")
    print(f"repo:  {repo}")
    print(f"graph: {len(nodes)} nodes / {len(links)} edges")
    for name, n, e in results:
        print(f"  {name}: {n} nodes / {e} edges")
    print(f"output: {out_dir}")


if __name__ == "__main__":
    main()